const queueData={providers:[{icon:'🍱',name:'Annapurna Tiffin',detail:'Patia, Bhubaneswar · Veg',meta:'Ready to activate',time:'18 min ago'},{icon:'🥘',name:'Home Bowl Kitchen',detail:'Khandagiri · Both',meta:'2 details missing',time:'1 hr ago'},{icon:'🍛',name:'Odia Tiffin Service',detail:'Jagamara · Both',meta:'Ready to activate',time:'3 hrs ago'},{icon:'🥗',name:'Green Spoon',detail:'Saheed Nagar · Veg',meta:'Awaiting pincode',time:'Yesterday'}],prices:[{icon:'₹',name:'Maa Home Kitchen',detail:'Lunch + Dinner',meta:'₹6,199 → ₹6,499',time:'38 min ago'},{icon:'₹',name:'Delight Non-Veg Meals',detail:'Dinner Only',meta:'₹3,299 → ₹3,499',time:'2 hrs ago'},{icon:'₹',name:'Swaad Ghar',detail:'Lunch Only',meta:'₹3,499 → ₹3,599',time:'Yesterday'}],areas:[{icon:'⌖',name:'Annapurna Tiffin',detail:'Add service area',meta:'751030 · Khandagiri',time:'46 min ago'},{icon:'⌖',name:'Home Bowl Kitchen',detail:'Expand delivery radius',meta:'5 km → 8 km',time:'Yesterday'}],menus:[{icon:'▤',name:'Swaad Ghar',detail:'Weekly menu · Lunch + Dinner',meta:'14 meal slots',time:'12 min ago'},{icon:'▤',name:'Odia Tiffin Service',detail:'Weekly menu · Lunch Only',meta:'7 meal slots',time:'29 min ago'},{icon:'▤',name:'Annapurna Tiffin',detail:'Weekly menu · Dinner Only',meta:'7 meal slots',time:'1 hr ago'},{icon:'▤',name:'Maa Home Kitchen',detail:'5 new alternatives',meta:'Menu update',time:'3 hrs ago'}],photos:[{icon:'🖼️',name:'Delight Non-Veg Meals',detail:'Meal and item photos',meta:'8 photos',time:'1 hr ago'},{icon:'🖼️',name:'Swaad Ghar',detail:'Provider logo',meta:'1 photo',time:'2 hrs ago'},{icon:'🖼️',name:'Maa Home Kitchen',detail:'Kitchen and packaging',meta:'3 photos',time:'Yesterday'}],capacity:[{icon:'◫',name:'Swaad Ghar',detail:'Capacity change request',meta:'Lunch: 80 → 100',time:'Today'}],audit:[{icon:'✓',name:'Provider activated',detail:'Swaad Ghar · by Ashutosh',meta:'Completed',time:'12 min ago'}]};
const subtitles={providers:'Approve providers after all mandatory operational details are ready.',prices:'Review provider price changes before they reach customers.',areas:'Control provider pincodes and delivery-radius changes.',menus:'Review weekly menus, fixed items and customer alternatives.',photos:'Only approved provider photos become visible to customers.',capacity:'Review changes that can affect active commitments.',audit:'Immutable history of important marketplace actions.'};
const login=document.querySelector('#login'),dashboard=document.querySelector('#dashboard'),nav=document.querySelector('#nav'),queueView=document.querySelector('#queueView'),overviewView=document.querySelector('#overviewView'),queueList=document.querySelector('#queueList'),title=document.querySelector('#pageTitle'),crumb=document.querySelector('#crumb');
const detailView=document.querySelector('#providerDetailView');
document.querySelector('#loginForm').addEventListener('submit',async e=>{e.preventDefault();try{if(ZomealAPI.configured){await ZomealAPI.login(document.querySelector('#email').value,document.querySelector('#password').value);await loadLiveQueue()}login.classList.add('hidden');dashboard.classList.remove('hidden');showToast(ZomealAPI.configured?'Secure session started':'Demo mode · add public Supabase key for live data')}catch(error){showToast(error.message)}});
document.querySelector('#logout').addEventListener('click',()=>{ZomealAPI.logout();dashboard.classList.add('hidden');login.classList.remove('hidden')});
document.querySelector('#menuButton').addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));
document.querySelector('#approvalInbox').innerHTML=[['♙','Provider activation','4 providers waiting','18 min ago','green'],['₹','Price changes','3 requests need review','38 min ago','blue'],['▧','Photo moderation','12 images waiting','1 hr ago','yellow'],['⌖','Service areas','2 pincode requests','Yesterday','purple']].map(x=>`<div class="inbox-item"><span class="badge-icon ${x[4]}">${x[0]}</span><div><strong>${x[1]}</strong><p>${x[2]}</p></div><time>${x[3]}</time></div>`).join('');
function hideViews(){overviewView.classList.add('hidden');queueView.classList.add('hidden');detailView.classList.add('hidden')}
function navigate(view){document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelector('.sidebar').classList.remove('open');hideViews();if(view==='overview'){overviewView.classList.remove('hidden');title.textContent='Good afternoon, Ashutosh';crumb.textContent='Overview';return}queueView.classList.remove('hidden');const label=view.charAt(0).toUpperCase()+view.slice(1);title.textContent=label+' approvals';crumb.textContent=label;document.querySelector('#queueSubtitle').textContent=subtitles[view];renderQueue(view)}
function renderQueue(view,filter=''){const rows=(queueData[view]||[]).filter(r=>(r.name+' '+r.detail+' '+r.meta).toLowerCase().includes(filter.toLowerCase()));queueList.innerHTML=rows.length?rows.map(r=>`<div class="queue-item"><span class="queue-avatar">${r.icon}</span><div><strong>${r.name}</strong><p>${r.detail}</p></div><div class="queue-meta"><small>REQUEST</small><strong>${r.meta}</strong></div><div class="queue-meta"><small>RECEIVED</small><strong>${r.time}</strong></div><div class="queue-actions"><button class="review">Review</button><button class="approve protected-action">Approve</button></div></div>`).join(''):`<div style="padding:50px;text-align:center;color:#78837d">No requests found.</div>`;queueList.querySelectorAll('.review').forEach(b=>b.onclick=openProviderDetail);bindProtectedActions()}
nav.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)navigate(b.dataset.view)});document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>navigate(b.dataset.go));document.querySelector('#queueSearch').addEventListener('input',e=>renderQueue(crumb.textContent.toLowerCase().replace('service areas','areas'),e.target.value));document.querySelectorAll('.filters button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');showToast(`${b.textContent} filter selected`)});
function showToast(message){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
async function loadLiveQueue(){if(!ZomealAPI.configured)return;const rows=await ZomealAPI.queue();Object.keys(queueData).forEach(k=>queueData[k]=[]);const map={PROVIDER:'providers',PRICE:'prices',SERVICE_AREA:'areas',MENU:'menus',MEDIA:'photos'};rows.forEach(r=>{const key=map[r.entity_type];if(key)queueData[key].push({id:r.id,type:r.entity_type,icon:r.entity_type==='PRICE'?'₹':'◉',name:r.provider_name,detail:r.entity_type.replace('_',' '),meta:r.status,time:new Date(r.submitted_at).toLocaleString()})})}
const weeklyMenus={lunch:[['Mon','Paneer Butter Masala','Rice · Dal · Salad · Achar'],['Tue','Chana Masala / Mix Veg','Rice or Roti · Dal · Bhaja'],['Wed','Kadai Paneer','Rice · Dal Tadka · Salad'],['Thu','Aloo Gobi / Rajma','Roti · Dal · Achar'],['Fri','Matar Paneer','Rice · Dal · Bharta'],['Sat','Seasonal Mix Veg','Roti or Paratha · Dal · Salad'],['Sun','Paneer Do Pyaza','Pulao · Dal · Raita']],dinner:[['Mon','Mix Veg / Egg Curry','Roti · Dal · Salad'],['Tue','Kadai Paneer','Paratha or Roti · Dal'],['Wed','Chana Masala','Roti · Dal · Achar'],['Thu','Paneer Curry / Soya Masala','Roti · Salad'],['Fri','Rajma','Rice · Dal · Bhaja'],['Sat','Veg Kofta','Puri or Roti · Dal'],['Sun','Mushroom Masala','Paratha · Dal · Salad']]};
const photos=[['Complete lunch thali','Meal photo','🍛'],['Paneer Butter Masala','Menu item','🥘'],['Sunday special meal','Package cover','🍱'],['Provider logo','Brand profile','AT'],['Kitchen preparation area','Kitchen','👩‍🍳'],['Food-grade tiffin packaging','Packaging','🥡']];
function renderWeeklyMenu(meal='lunch'){document.querySelector('#weeklyMenu').innerHTML=weeklyMenus[meal].map(r=>`<div class="menu-day"><strong>${r[0]}</strong><div><small>Changing main course</small><p class="choice-tag">${r[1]}</p></div><div><small>Fixed / carb items</small><p>${r[2]}</p></div></div>`).join('')}
function renderPhotos(){document.querySelector('#photoGallery').innerHTML=photos.map((p,i)=>`<article class="photo-card" data-photo="${i}"><div class="food-photo">${p[2]}</div><div><strong>${p[0]}</strong><small>${p[1]} · Pending review</small></div></article>`).join('');document.querySelectorAll('.photo-card').forEach(c=>c.onclick=()=>openPhoto(Number(c.dataset.photo)))}
function openProviderDetail(){hideViews();detailView.classList.remove('hidden');title.textContent='Review provider';crumb.textContent='Providers / Annapurna Tiffin';renderWeeklyMenu();renderPhotos();window.scrollTo(0,0)}
document.querySelector('#backToQueue').onclick=()=>navigate('providers');document.querySelectorAll('.meal-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.meal-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderWeeklyMenu(b.dataset.meal)});
function openPhoto(i){const p=photos[i],modal=document.querySelector('#photoModal');document.querySelector('#modalImage').textContent=p[2];document.querySelector('#modalTitle').textContent=p[0];document.querySelector('#modalMeta').textContent=`${p[1]} · Uploaded by Annapurna Tiffin · Pending review`;modal.classList.remove('hidden')}
document.querySelector('#closePhoto').onclick=()=>document.querySelector('#photoModal').classList.add('hidden');
function bindProtectedActions(){document.querySelectorAll('.protected-action').forEach(b=>b.onclick=()=>showToast('Approval is protected until audited server actions are connected'))}bindProtectedActions();document.querySelectorAll('.reject-button').forEach(b=>b.onclick=()=>showToast('Change request form is ready for backend connection'));
const manualModal=document.querySelector('#manualProviderModal'),weekDays=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
document.querySelector('#manualWeek').innerHTML=weekDays.map(day=>`<div class="manual-day"><strong>${day}</strong><input placeholder="Main course / alternatives"><input placeholder="Fixed items: Dal, rice, salad..."></div>`).join('');
document.querySelectorAll('.manual-provider-button').forEach(b=>b.onclick=()=>manualModal.classList.remove('hidden'));document.querySelector('#closeManual').onclick=()=>manualModal.classList.add('hidden');
document.querySelector('#copyMonday').onclick=()=>{const f=document.querySelectorAll('.manual-day input');for(let i=2;i<f.length;i+=2){f[i].value=f[0].value;f[i+1].value=f[1].value}showToast('Monday menu copied to all days')};
document.querySelector('#saveDraft').onclick=()=>showToast(ZomealAPI.configured?'Use Save provider to persist this draft':'Draft preview · configure Supabase for permanent saving');document.querySelector('#manualProviderForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),name=fd.get('providerName'),payload={display_name:name,contact_person_name:e.target.querySelectorAll('input')[1].value,support_phone:e.target.querySelectorAll('input')[2].value,dietary_type:'VEG',business_address_line:e.target.querySelectorAll('input')[3].value,business_city:'Bhubaneswar',business_state:'Odisha'};try{if(ZomealAPI.configured)await ZomealAPI.createProvider(payload);manualModal.classList.add('hidden');queueData.providers.unshift({icon:'＋',name,detail:'Manually added by admin',meta:'Draft · Needs review',time:'Just now'});navigate('providers');showToast(`${name} saved to the review queue`)}catch(error){showToast(error.message)}};
const manualTitle=manualModal.querySelector('.manual-head h2'),manualDescription=manualModal.querySelector('.manual-head p:last-child'),manualForm=document.querySelector('#manualProviderForm');
document.querySelector('#editProvider').onclick=()=>{manualTitle.textContent='Edit provider data';manualDescription.textContent='Admin changes will return to review and be included in the audit history.';const inputs=manualForm.querySelectorAll('input');manualForm.elements.providerName.value='Annapurna Tiffin';inputs[1].value='Priya Dash';inputs[2].value='9876543210';inputs[3].value='Plot 42, KIIT Square, Patia';const pinField=[...inputs].find(i=>i.placeholder.includes('751030'));if(pinField)pinField.value='751024, 751016, 751031';const menuFields=document.querySelectorAll('.manual-day input');weeklyMenus.lunch.forEach((r,i)=>{menuFields[i*2].value=r[1];menuFields[i*2+1].value=r[2]});manualModal.classList.remove('hidden');showToast('Editing Annapurna Tiffin')};
document.querySelectorAll('.manual-provider-button').forEach(b=>b.addEventListener('click',()=>{manualTitle.textContent='Add a provider';manualDescription.textContent='Enter information received by phone, WhatsApp or in person.'}));
