(function(){
const form=document.querySelector('#manualProviderForm'),status=document.createElement('div');let timer=null,loading=false,lastSaved='';
status.className='autosave-status';status.innerHTML='<span></span><strong>All changes saved</strong>';form.querySelector('.manual-footer').prepend(status);
function serializableDraft(){const payload=providerPayload(form);payload.menu=payload.menu.map(day=>({...day,main_courses:day.main_courses.map(({photo,...item})=>({...item,photo_pending:Boolean(photo),photo_name:photo?.name||null}))}));return payload}
async function saveNow(){if(loading||!ZomealAPI.configured)return;const payload=serializableDraft(),json=JSON.stringify(payload);if(json===lastSaved)return;status.dataset.state='saving';status.querySelector('strong').textContent='Saving changes…';try{await ZomealAPI.saveFormDraft(editingProviderId||null,'PROVIDER_ONBOARDING',payload);lastSaved=json;status.dataset.state='saved';status.querySelector('strong').textContent=`Saved ${new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`}catch(error){status.dataset.state='error';status.querySelector('strong').textContent='Could not save draft';showToast(error.message)}}
function schedule(){if(loading)return;status.dataset.state='pending';status.querySelector('strong').textContent='Unsaved changes';clearTimeout(timer);timer=setTimeout(saveNow,700)}
function fillBasics(p){if(!p)return;form.elements.providerName.value=p.display_name||'';const basic=form.querySelectorAll(':scope > section input');if(basic[1])basic[1].value=p.contact_person_name||'';if(basic[2])basic[2].value=p.support_phone||'';if(basic[3])basic[3].value=p.business_address_line||'';if(basic[4])basic[4].value=p.business_city||'';if(basic[5])basic[5].value=p.business_state||'';const pin=[...form.querySelectorAll('input')].find(i=>i.placeholder.includes('751030'));if(pin)pin.value=(p.pincodes||[]).map(x=>x.code||x).join(', ')}
async function resume(){if(!ZomealAPI.configured)return;loading=true;status.dataset.state='loading';status.querySelector('strong').textContent='Checking saved draft…';try{const draft=await ZomealAPI.getFormDraft(editingProviderId||null,'PROVIDER_ONBOARDING');if(draft?.payload&&Object.keys(draft.payload).length){fillBasics(draft.payload);ZomealMenuBuilder.loadMenu(draft.payload.menu||[]);lastSaved=JSON.stringify(draft.payload);status.dataset.state='saved';status.querySelector('strong').textContent=`Draft restored · ${new Date(draft.updated_at).toLocaleString()}`;showToast('Your last saved draft has been restored')}else{status.dataset.state='saved';status.querySelector('strong').textContent='New draft · changes save automatically'}}catch(error){status.dataset.state='error';status.querySelector('strong').textContent='Draft unavailable';showToast(error.message)}finally{loading=false}}
form.addEventListener('input',schedule);form.addEventListener('change',schedule);
document.querySelectorAll('.manual-provider-button').forEach(button=>{const open=button.onclick;button.onclick=e=>{open?.call(button,e);setTimeout(resume,0)}});
const edit=document.querySelector('#editProvider'),openEdit=edit.onclick;edit.onclick=e=>{openEdit?.call(edit,e);setTimeout(resume,0)};
document.querySelector('#saveDraft').onclick=async()=>{await saveNow();showToast('Draft saved. You can safely continue later.')};
window.addEventListener('beforeunload',()=>{if(timer)saveNow()});
})();
