window.ZomealChanges=(()=>{
const list=document.querySelector('#changeRequestList'),detail=document.querySelector('#changeDetailHost');let status='PENDING',search='',rows=[],current=null,edited=null;
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const nice=value=>String(value??'—').replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase());
const same=(a,b)=>JSON.stringify(a??null)===JSON.stringify(b??null);
const field=(label,key,before,after,type='text')=>`<label class="diff-field ${same(before,after)?'unchanged':'changed'}"><span>${label}${same(before,after)?'':' · changed'}</span><small>Before: ${esc(before||'—')}</small><input type="${type}" data-key="${key}" value="${esc(after??'')}"></label>`;
async function load(){list.innerHTML='<div class="change-empty">Loading provider requests…</div>';try{rows=await ZomealAPI.providerChangeQueue(status,search||null);document.querySelector('#changeNavCount').textContent=rows.filter(x=>x.status==='PENDING').length;render()}catch(error){list.innerHTML=`<div class="change-empty error"><b>Could not load requests</b><span>${esc(error.message)}</span></div>`}}
function render(){list.innerHTML=rows.length?rows.map(row=>`<article class="change-request"><div class="change-provider-mark">${esc(row.provider_name.split(' ').map(x=>x[0]).slice(0,2).join(''))}</div><div><strong>${esc(row.provider_name)}</strong><p>Full business listing update · ${new Date(row.requested_at).toLocaleString()}</p><div class="change-counts"><span>${row.price_count} prices</span><span>${row.menu_item_count} menu entries</span><span>${row.photo_count} photos</span></div></div><span class="state-chip ${row.status.toLowerCase()}">${nice(row.status)}</span><button data-id="${row.id}" class="review-change">Review changes →</button></article>`).join(''):'<div class="change-empty"><b>No requests in this view</b><span>Provider edits will appear here after submission.</span></div>';list.querySelectorAll('.review-change').forEach(button=>button.onclick=()=>open(button.dataset.id))}
async function open(id){hideViews();document.querySelector('#changeDetailView').classList.remove('hidden');document.querySelector('#pageTitle').textContent='Review provider changes';document.querySelector('#crumb').textContent='Provider changes / Review';detail.innerHTML='<div class="change-empty">Building before-and-after comparison…</div>';try{current=await ZomealAPI.providerChangeDetail(id);edited=structuredClone(current.request.payload);renderDetail()}catch(error){detail.innerHTML=`<div class="change-empty error"><b>Could not load request</b><span>${esc(error.message)}</span></div>`}}
function packageAfter(kind){const map={LUNCH_ONLY:['lunchEnabled','lunchPrice'],DINNER_ONLY:['dinnerEnabled','dinnerPrice'],LUNCH_AND_DINNER:['bothEnabled','bothPrice']},keys=map[kind];return keys?{enabled:!!edited[keys[0]],price:edited[keys[1]]}:{} }
function beforeDishes(dayIndex,slot){const rows=current?.before?.menu||[],row=rows.find(x=>Number(x.day)===dayIndex+1&&String(x.slot).toUpperCase()===slot.toUpperCase());return (row?.items||[]).filter(item=>String(item.category).toUpperCase()==='MAIN_COURSE')}
const diet=value=>String(value||'VEG').toUpperCase().replaceAll('-','_');
function sameDish(before,after){return !!before&&same(String(before.name||'').trim(),String(after.name||'').trim())&&same(String(before.description||'').trim(),String(after.description||'').trim())&&same(diet(before.foodType||before.dietary_type),diet(after.foodType))}
function renderDetail(){const before=current.before||{},p=before.profile||{},pending=current.pending_photos||[],packages=before.packages||[],menus=edited.menus||[];if(!Array.isArray(edited.photoEdits))edited.photoEdits=pending.map(photo=>({id:photo.id,altText:photo.alt_text||'',publish:true}));detail.innerHTML=`
  <section class="change-summary panel"><div><p class="eyebrow green">${esc(current.request.status)} REQUEST</p><h2>${esc(edited.businessName||p.businessName)}</h2><p>Submitted ${new Date(current.request.requested_at).toLocaleString()}</p></div><div><b>${pending.length}</b><span>new photos</span></div><div><b>${menus.length}</b><span>menu days</span></div><div><b>${packages.length}</b><span>current packages</span></div></section>
  <div class="change-layout"><div>
    <section class="panel change-card"><div class="change-card-head"><div><h3>Business profile</h3><p>Changed fields are highlighted. Verified login phone and bank details cannot be edited here.</p></div><span class="change-legend">Before → requested</span></div><div class="change-form-grid">
      ${field('Business name','businessName',p.businessName,edited.businessName)}${field('Contact person','contactName',p.contactName,edited.contactName)}
      ${field('Address','address',p.address,edited.address)}${field('City','city',p.city,edited.city)}${field('State','state',p.state,edited.state)}${field('Business pincode','pincode',p.pincode,edited.pincode)}
    </div></section>
    <section class="panel change-card"><div class="change-card-head"><div><h3>Packages & prices</h3><p>Customer prices update only after approval.</p></div></div><div class="package-diffs">${['LUNCH_ONLY','LUNCH_AND_DINNER','DINNER_ONLY'].map(kind=>{const old=packages.find(x=>x.kind===kind)||{},next=packageAfter(kind),map={LUNCH_ONLY:['lunchEnabled','lunchPrice'],DINNER_ONLY:['dinnerEnabled','dinnerPrice'],LUNCH_AND_DINNER:['bothEnabled','bothPrice']},keys=map[kind];return `<article class="package-diff ${same(!!old.enabled,next.enabled)&&same(String(old.price??''),String(next.price??''))?'':'changed'}"><div><strong>${nice(kind)}</strong><small>Before: ${old.enabled?'Active · ₹'+(old.price??'—'):'Not offered'}</small></div><label><input type="checkbox" data-key="${keys[0]}" ${next.enabled?'checked':''}> Offered</label><label>Monthly ₹<input type="number" min="1" data-key="${keys[1]}" value="${esc(next.price||'')}"></label></article>`}).join('')}</div></section>
    <section class="panel change-card"><div class="change-card-head"><div><h3>Monday–Sunday menu</h3><p>Edit dish names, descriptions and dietary tags before publishing.</p></div></div><div class="requested-menu">${menus.map((day,dayIndex)=>menuDay(day,dayIndex)).join('')}</div></section>
    <section class="panel change-card"><div class="change-card-head"><div><h3>Requested photographs</h3><p>Edit descriptions or exclude an unsuitable photo. Every upload remains private until approval.</p></div><span>${pending.length} uploads</span></div><div id="changePhotos" class="change-photos">${pending.length?pending.map((photo,index)=>`<article><div class="change-photo" data-path="${encodeURIComponent(photo.storage_path)}">Loading…</div><strong>${esc(photo.dish_name||nice(photo.media_type))}</strong><label class="photo-alt">Description<input data-photo-alt="${index}" value="${esc(edited.photoEdits[index]?.altText||'')}"></label><label class="photo-publish"><input type="checkbox" data-photo-publish="${index}" ${edited.photoEdits[index]?.publish!==false?'checked':''}> Publish after approval</label><span>${nice(photo.status)}</span></article>`).join(''):'<div class="change-empty">No new photos in this request.</div>'}</div></section>
  </div><aside><section class="panel decision-card"><h3>Publishing checklist</h3><p>✓ Current approved listing stays live during review</p><p>✓ One decision covers profile, prices, menus and photos</p><p>✓ Approval creates an audit entry</p><p>✓ Rejection sends the provider your reason</p><label>Internal review note<textarea id="changeReviewNote" placeholder="Optional on approval; required on rejection">${esc(current.request.review_note||'')}</textarea></label></section></aside></div>`;
  bindInputs();loadPhotos();const pendingState=current.request.status==='PENDING';['saveChangeEdits','rejectChange','approveChange'].forEach(id=>document.querySelector('#'+id).disabled=!pendingState)}
function menuDay(day,dayIndex){const changed=['lunch','dinner'].reduce((count,slot)=>{const old=beforeDishes(dayIndex,slot),next=day[slot]||[];return count+Math.max(old.length,next.length)-next.filter((dish,index)=>sameDish(old[index],dish)).length},0);return `<details class="change-menu-day ${changed?'changed':'unchanged'}" ${dayIndex===0?'open':''}><summary><b>${esc(day.day)}</b><span>${changed?changed+' actual change'+(changed===1?'':'s'):'No menu changes'}</span></summary>${['lunch','dinner'].map(slot=>{const old=beforeDishes(dayIndex,slot);return `<div class="change-slot"><h4>${nice(slot)}</h4>${(day[slot]||[]).map((dish,dishIndex)=>{const unchanged=sameDish(old[dishIndex],dish);return `<div class="dish-edit ${unchanged?'unchanged':'changed'}"><span>${dishIndex+1}</span><input data-menu="${dayIndex}.${slot}.${dishIndex}.name" value="${esc(dish.name)}" placeholder="Dish name"><select data-menu="${dayIndex}.${slot}.${dishIndex}.foodType"><option ${diet(dish.foodType)==='VEG'?'selected':''}>VEG</option><option value="NON_VEG" ${diet(dish.foodType)==='NON_VEG'?'selected':''}>NON-VEG</option><option ${diet(dish.foodType)==='VEGAN'?'selected':''}>VEGAN</option></select><input data-menu="${dayIndex}.${slot}.${dishIndex}.description" value="${esc(dish.description||'')}" placeholder="Description (optional)"><small>${unchanged?'Using existing approved dish':'Changed'}</small></div>`}).join('')||'<p class="muted">Not offered</p>'}</div>`}).join('')}</details>`}
function bindInputs(){detail.querySelectorAll('[data-key]').forEach(input=>input.oninput=()=>{edited[input.dataset.key]=input.type==='checkbox'?input.checked:input.value});detail.querySelectorAll('[data-menu]').forEach(input=>input.oninput=()=>{const [day,slot,dish,key]=input.dataset.menu.split('.');edited.menus[Number(day)][slot][Number(dish)][key]=input.value});detail.querySelectorAll('[data-photo-alt]').forEach(input=>input.oninput=()=>edited.photoEdits[Number(input.dataset.photoAlt)].altText=input.value);detail.querySelectorAll('[data-photo-publish]').forEach(input=>input.oninput=()=>edited.photoEdits[Number(input.dataset.photoPublish)].publish=input.checked)}
async function loadPhotos(){for(const frame of detail.querySelectorAll('.change-photo'))try{const url=await ZomealAPI.mediaUrl(decodeURIComponent(frame.dataset.path));frame.innerHTML=`<img src="${url}" alt="Provider requested photo">`}catch{frame.textContent='Photo unavailable'}}
async function save(){try{await ZomealAPI.saveProviderChange(current.request.id,edited,document.querySelector('#changeReviewNote').value.trim()||null);showToast('Admin edits saved to the pending request')}catch(error){showToast(error.message)}}
async function decide(decision){const note=document.querySelector('#changeReviewNote').value.trim();if(decision==='REJECTED'&&!note)return showToast('Write a clear rejection reason for the provider');const message=decision==='APPROVED'?'Publish this complete replacement listing to customers now?':'Reject this request and notify the provider?';if(!confirm(message))return;try{await ZomealAPI.reviewProviderChange(current.request.id,decision,note||null,edited);showToast(decision==='APPROVED'?'Changes approved and published':'Request rejected and provider notified');status='PENDING';document.querySelectorAll('.change-filters button').forEach(x=>x.classList.toggle('active',x.dataset.status==='PENDING'));navigate('changes')}catch(error){showToast(error.message)}}
document.querySelector('#refreshChanges').onclick=load;document.querySelector('#backToChanges').onclick=()=>navigate('changes');document.querySelector('#saveChangeEdits').onclick=save;document.querySelector('#approveChange').onclick=()=>decide('APPROVED');document.querySelector('#rejectChange').onclick=()=>decide('REJECTED');
document.querySelectorAll('.change-filters button').forEach(button=>button.onclick=()=>{status=button.dataset.status;document.querySelectorAll('.change-filters button').forEach(x=>x.classList.toggle('active',x===button));load()});let timer;document.querySelector('#changeSearch').oninput=event=>{search=event.target.value;clearTimeout(timer);timer=setTimeout(load,300)};
return{load,open};
})();
