/* Production-only CEO charts. Money remains in paise until formatted. */
(() => {
 'use strict';
 const DAY=86400000;
 const metrics=[['zomeal_revenue_paise','Zomeal revenue','Fees + delivered-meal commission'],['captured_paise','Customer collections','Captured payments; not revenue'],['commission_paise','Commission','Includes ledger reversals'],['delivered_gmv_paise','Delivered meal value','Net of ledger reversals'],['provider_net_paise','Provider earnings','Not bank payouts'],['platform_fee_paise','Platform fees','Customer-paid fees'],['captured_count','Captured payments','Payment count'],['failed_count','Failed payments','Current failed status']];
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const date=s=>new Date(s+'T00:00:00Z');
 const iso=d=>d.toISOString().slice(0,10);
 const today=()=>iso(new Date(Date.now()+330*60000));
 const fmt=(v,key='paise')=>v==null?'Unavailable':key.endsWith('count')?Number(v).toLocaleString('en-IN'):new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(v/100);
 function range(from,to){if(!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(to)||isNaN(+date(from))||isNaN(+date(to))||iso(date(from))!==from||iso(date(to))!==to)throw Error('Choose valid dates.');const n=Math.round((date(to)-date(from))/DAY)+1;if(n<1||n>367)throw Error('Choose a range of 1–367 days.');if(to>today())throw Error('Reports cannot include future dates.');return {from:iso(new Date(+date(from)-n*DAY)),to:iso(new Date(+date(from)-DAY)),days:n};}
 function total(rows,key){if(!Array.isArray(rows)||rows.some(r=>r[key]==null||!Number.isFinite(Number(r[key]))))return null;return rows.reduce((a,r)=>a+Number(r[key]),0);}
 function change(now,before,key){if(now==null||before==null)return {text:'Comparison unavailable',direction:'neutral'};const d=now-before;const text=before>0?`${d>0?'+':''}${(100*d/before).toFixed(1)}%`:before===0?(now===0?'No change':'No prior activity'):'Prior value negative';return {text:`${text} · ${d>0?'+':''}${fmt(d,key)}`,direction:d===0?'neutral':(key==='failed_count'?d<0:d>0)?'up':'down'};}
 function aggregate(rows,unit){const groups=new Map();for(const r of rows){const d=date(r.report_date);let key=r.report_date;if(unit==='week'){d.setUTCDate(d.getUTCDate()-(d.getUTCDay()+6)%7);key=iso(d);}if(unit==='month')key=r.report_date.slice(0,7);if(!groups.has(key))groups.set(key,{label:key,start:r.report_date,end:r.report_date,rows:[]});const g=groups.get(key);g.end=r.report_date;g.rows.push(r);}return [...groups.values()].map(g=>({...g,...Object.fromEntries(metrics.map(([k])=>[k,total(g.rows,k)]))}));}
 const states=new WeakMap();
 function chart(groups,previous,key){const a=groups.map(g=>g[key]),b=previous.map(g=>g[key]);if([...a,...b].some(v=>v==null))return '<p class="growth-empty">Some values are unavailable. See the data table.</p>';const lo=Math.min(0,...a,...b),hi=Math.max(1,...a,...b),x=i=>56+i*660/Math.max(1,Math.max(a.length,b.length)-1),y=v=>196-(v-lo)*164/(hi-lo);let svg='';for(let i=0;i<4;i++){const v=lo+(hi-lo)*i/3;svg+=`<line x1="56" x2="716" y1="${y(v)}" y2="${y(v)}" class="growth-gridline"/><text x="50" y="${y(v)+4}" text-anchor="end">${esc(key.endsWith('count')?v.toFixed(0):new Intl.NumberFormat('en-IN',{notation:'compact',maximumFractionDigits:1}).format(v/100))}</text>`;}
 [b,a].forEach((values,j)=>{if(!values.length)return;svg+=`<polyline class="growth-line ${j?'current':'previous'}" points="${values.map((v,i)=>`${x(i)},${y(v)}`).join(' ')}"/>`;values.forEach((v,i)=>{const g=(j?groups:previous)[i];svg+=`<circle class="${j?'current':'previous'}" cx="${x(i)}" cy="${y(v)}" r="3"><title>${esc(`${g.start} to ${g.end}: ${fmt(v,key)}`)}</title></circle>`;});});
 svg+=`<text x="56" y="224">First bucket</text><text x="716" y="224" text-anchor="end">Last bucket</text>`;return `<svg viewBox="0 0 750 240" role="img" aria-label="${esc(metrics.find(m=>m[0]===key)[1])} trend. Exact figures in the data table below.">${svg}</svg>`;}
 function draw(host){const s=states.get(host);if(!s?.current)return;const d=s.current,rows=d.history,prior=s.previous?.history;const grouped=aggregate(rows,s.unit),previous=aggregate(prior||[],s.unit),selected=metrics.find(m=>m[0]===s.key);const sum=k=>total(rows,k);const fees=sum('platform_fee_paise'),commission=sum('commission_paise'),rev=sum('zomeal_revenue_paise');const split=fees!=null&&commission!=null&&fees>=0&&commission>=0&&fees+commission>0;const share=split?commission/(fees+commission)*100:0;
 host.innerHTML=`<div class="growth-heading"><div><span class="growth-eyebrow">ZOMEAL · BUSINESS PULSE</span><h3>See the story behind the numbers</h3><p>${esc(d.from_date)} – ${esc(d.to_date)} · IST</p></div><div class="growth-presets" aria-label="Reporting range">${[['day','Today'],['week','Last 7 days'],['month','This month']].map(([v,t])=>`<button type="button" data-range="${v}">${t}</button>`).join('')}</div></div><p class="growth-note">Compared with ${esc(s.comparison.from)} – ${esc(s.comparison.to)} (${s.comparison.days} days). ${d.to_date===today()?'Today is incomplete; growth is provisional. ':''}Revenue is not profit: company expenses and taxes are not included.</p><p class="growth-status" role="status">${esc(s.error||(!s.previous?'Loading previous period…':''))}</p>
 <div class="growth-kpis">${metrics.map(([k,t,h])=>{const v=sum(k),delta=change(v,prior?total(prior,k):null,k);return `<button type="button" class="growth-kpi" data-metric="${k}" aria-pressed="${s.key===k}"><span>${t}</span><strong>${fmt(v,k)}</strong><small class="growth-delta ${delta.direction}">${esc(delta.text)}</small><small>${h}</small></button>`;}).join('')}</div>
 <div class="growth-layout"><article class="growth-card growth-trend"><div class="growth-card-head"><div><h3>${selected[1]} trend</h3><p>Same scale · aligned by bucket position</p></div><div class="growth-switch" aria-label="Group chart by">${['day','week','month'].map(u=>`<button type="button" data-unit="${u}" aria-pressed="${s.unit===u}">${u==='day'?'Daily':u==='week'?'Weekly':'Monthly'}</button>`).join('')}</div></div><div class="growth-legend"><span>● Selected period</span><span>┄ Previous period</span></div>${chart(grouped,previous,s.key)}<small>Weeks start Monday. First/last weeks or months may be partial; totals use only selected dates. Growth cards compare equal day counts, not individual buckets.</small></article>
 <article class="growth-card"><h3>Where revenue comes from</h3><p>Selected-period contribution</p>${split?`<div class="growth-donut" style="--share:${share}%"><div><strong>${fmt(rev)}</strong><small>Zomeal revenue</small></div></div>`:'<div class="growth-empty">No positive revenue mix to plot. Signed amounts are shown below.</div>'}<div class="growth-breakdown"><span>● Commission</span><b>${fmt(commission)}</b><span>● Platform fees</span><b>${fmt(fees)}</b></div><small>Refunded-order value is not deducted as a refund amount. Commission follows the finance ledger, including reversals.</small></article>
 <article class="growth-card growth-wide"><h3>Revenue alongside collections</h3><p>Customer collections fund the marketplace; only fees and commission count as Zomeal revenue.</p><div class="growth-bars">${(()=>{const keys=['captured_paise','delivered_gmv_paise','provider_net_paise','zomeal_revenue_paise'];const max=Math.max(1,...keys.map(k=>Math.abs(sum(k)||0)));return keys.map(k=>`<div><span>${metrics.find(m=>m[0]===k)[1]}</span><div class="growth-track"><i style="width:${Math.abs(sum(k)||0)/max*100}%" class="${sum(k)<0?'negative':''}"></i></div><b>${fmt(sum(k))}</b></div>`).join('');})()}</div><small>Bar lengths show magnitude; negative values are marked in red. These categories overlap and must not be added together.</small></article></div>
 <details class="growth-card growth-data"><summary>View exact chart data · ${selected[1]}</summary><div class="growth-table"><table><thead><tr><th>Period</th><th>Dates included</th><th>${selected[1]}</th></tr></thead><tbody>${[[grouped,'Selected'],[previous,'Previous']].flatMap(([arr,label])=>arr.map(g=>`<tr><td>${label}</td><td>${g.start} – ${g.end}</td><td>${fmt(g[s.key],s.key)}</td></tr>`)).join('')}</tbody></table></div></details>`;
 host.querySelectorAll('[data-metric]').forEach(b=>b.onclick=()=>{s.key=b.dataset.metric;draw(host);host.querySelector(`[data-metric="${s.key}"]`).focus();});host.querySelectorAll('[data-unit]').forEach(b=>b.onclick=()=>{s.unit=b.dataset.unit;draw(host);host.querySelector(`[data-unit="${s.unit}"]`).focus();});host.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{const to=today();const from=b.dataset.range==='day'?to:b.dataset.range==='month'?to.slice(0,8)+'01':iso(new Date(+date(to)-6*DAY));s.onRange?.(from,to);});
 }
 function clear(host,message='Loading production trends…'){if(!host)return;states.delete(host);host.classList.add('growth-dashboard');host.textContent=message;}
 async function render(host,d,onRange){clear(host);try{if(!Array.isArray(d.history)||!d.history.length)throw Error('No daily history returned. Refresh or check reporting access.');const comparison=range(d.from_date,d.to_date);const s={current:d,comparison,key:'zomeal_revenue_paise',unit:comparison.days>90?'month':comparison.days>31?'week':'day',onRange};states.set(host,s);draw(host);try{s.previous=await window.ZomealAPI.businessDashboard(comparison.from,comparison.to);if(!Array.isArray(s.previous.history)||s.previous.history.length!==comparison.days)throw Error('Previous-period data incomplete');}catch(e){s.previous=null;s.error='Previous-period comparison unavailable. Refresh to retry.';}if(states.get(host)===s)draw(host);}catch(e){clear(host,e.message);}}
 window.ZomealGrowth={render,clear,range};
 if(typeof module!=='undefined')module.exports={range,total,change,aggregate};
})();
