window.ZomealLeads=(()=>{
  const list=document.querySelector('#leadList'),stats=document.querySelector('#leadStats'),search=document.querySelector('#leadSearch');
  let rows=[],status='',timer;
  const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const nice=value=>String(value||'').replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
  const interest={CUSTOMER:'Looking for meals',PROVIDER:'Provider enquiry',LAUNCH_ALERT:'Launch alert'};
  function filtered(){const query=search.value.trim().toLowerCase();return rows.filter(row=>(!status||row.status===status)&&(!query||`${row.full_name} ${row.phone} ${row.pincode} ${row.locality||''}`.toLowerCase().includes(query)))}
  function renderStats(){const count=key=>rows.filter(row=>row.status===key).length;stats.innerHTML=`<article><span>✦</span><div><small>Total leads</small><b>${rows.length}</b></div></article><article><span>●</span><div><small>New</small><b>${count('NEW')}</b></div></article><article><span>☎</span><div><small>Contacted</small><b>${count('CONTACTED')}</b></div></article><article><span>✓</span><div><small>Converted</small><b>${count('CONVERTED')}</b></div></article>`;document.querySelector('#leadNavCount').textContent=count('NEW')}
  function render(){const visible=filtered();list.innerHTML=visible.length?visible.map(row=>{const phone=String(row.phone).replace(/\D/g,'');return `<article class="lead-row" data-id="${row.id}"><div class="lead-person"><span>${esc(row.full_name).split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()}</span><div><strong>${esc(row.full_name)}</strong><a href="tel:+91${phone}">+91 ${phone}</a></div></div><div><strong>${esc(row.pincode)}</strong><small>${esc(row.locality||'Locality not supplied')}</small></div><div><span class="interest ${row.interest.toLowerCase()}">${esc(interest[row.interest]||nice(row.interest))}</span><small>${esc(row.source)}</small></div><div><strong>${new Date(row.created_at).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}</strong><small>${new Date(row.created_at).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}</small></div><div class="lead-actions"><select aria-label="Status for ${esc(row.full_name)}"><option value="NEW" ${row.status==='NEW'?'selected':''}>New</option><option value="CONTACTED" ${row.status==='CONTACTED'?'selected':''}>Contacted</option><option value="CONVERTED" ${row.status==='CONVERTED'?'selected':''}>Converted</option><option value="CLOSED" ${row.status==='CLOSED'?'selected':''}>Closed</option></select><a class="call-lead" href="tel:+91${phone}" title="Call">☎</a><a class="whatsapp-lead" href="https://wa.me/91${phone}?text=${encodeURIComponent(`Hello ${row.full_name}, thank you for your interest in Zomeal.`)}" target="_blank" rel="noopener" title="Open WhatsApp">◉</a></div></article>`}).join(''):'<div class="lead-empty"><span>🌱</span><b>No leads in this view</b><p>New website enquiries will appear here automatically.</p></div>';list.querySelectorAll('select').forEach(select=>select.onchange=()=>update(select.closest('.lead-row').dataset.id,select.value,select))}
  async function update(id,next,select){select.disabled=true;try{await ZomealAPI.updateWebsiteLead(id,next);const row=rows.find(x=>x.id===id);if(row)row.status=next;renderStats();render();showToast(`Lead marked ${nice(next).toLowerCase()}`)}catch(error){showToast(error.message);select.disabled=false}}
  async function load(){list.innerHTML='<div class="lead-empty"><span class="lead-loader"></span><b>Loading website leads…</b></div>';try{rows=await ZomealAPI.websiteLeads(null,null)||[];renderStats();render()}catch(error){list.innerHTML=`<div class="lead-empty error"><b>Could not load early access leads</b><p>${esc(error.message)}</p><button id="retryLeads">Retry</button></div>`;document.querySelector('#retryLeads').onclick=load}}
  function exportCsv(){const data=filtered();if(!data.length)return showToast('There are no leads to export');const headers=['Name','Phone','Pincode','Locality','Interest','Status','Consent at','Created at'];const quote=value=>`"${String(value??'').replaceAll('"','""')}"`;const csv=[headers,...data.map(row=>[row.full_name,row.phone,row.pincode,row.locality,interest[row.interest]||row.interest,row.status,row.consent_at,row.created_at])].map(line=>line.map(quote).join(',')).join('\r\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`zomeal-website-leads-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url);showToast(`Exported ${data.length} leads`)}
  document.querySelector('#refreshLeads').onclick=load;document.querySelector('#exportLeads').onclick=exportCsv;document.querySelectorAll('#leadFilters button').forEach(button=>button.onclick=()=>{document.querySelectorAll('#leadFilters button').forEach(x=>x.classList.remove('active'));button.classList.add('active');status=button.dataset.status;render()});search.oninput=()=>{clearTimeout(timer);timer=setTimeout(render,180)};
  return{load};
})();
