window.ZomealAPI=(()=>{const c=window.ZOMEAL_CONFIG||{},configured=c.supabaseAnonKey&&!c.supabaseAnonKey.startsWith('YOUR_');let token=null;
async function request(path,{method='GET',body,auth=true}={}){const headers={apikey:c.supabaseAnonKey,'Content-Type':'application/json'};if(auth&&token)headers.Authorization=`Bearer ${token}`;const r=await fetch(`${c.supabaseUrl}${path}`,{method,headers,body:body?JSON.stringify(body):undefined});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).message||`Request failed (${r.status})`);const text=await r.text();return text?JSON.parse(text):null}
async function login(email,password){const s=await request('/auth/v1/token?grant_type=password',{method:'POST',body:{email,password},auth:false});token=s.access_token;sessionStorage.setItem('zomeal_admin_session',JSON.stringify(s));const roles=await request('/rest/v1/user_roles?select=role');if(!roles.some(x=>['ADMIN','OPERATIONS','FINANCE'].includes(x.role))){logout();throw new Error('This account is not authorized for Zomeal Admin')}return s}
async function restore(){try{let s=JSON.parse(sessionStorage.getItem('zomeal_admin_session'));if(!s?.access_token)return false;const expiresAt=Number(s.expires_at||0);if(expiresAt&&expiresAt<=Math.floor(Date.now()/1000)+30&&s.refresh_token){s=await request('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:s.refresh_token},auth:false});sessionStorage.setItem('zomeal_admin_session',JSON.stringify(s))}token=s.access_token;const roles=await request('/rest/v1/user_roles?select=role');if(!roles.some(x=>['ADMIN','OPERATIONS','FINANCE'].includes(x.role))){logout();return false}return true}catch{logout();return false}}function logout(){token=null;sessionStorage.removeItem('zomeal_admin_session')}
async function queue(){return request('/rest/v1/admin_approval_queue?select=*&order=submitted_at.asc')}
async function createProvider(payload){return request('/rest/v1/rpc/admin_create_provider_draft',{method:'POST',body:{payload}})}
async function updateProvider(id,payload,reason){return request('/rest/v1/rpc/admin_update_provider',{method:'POST',body:{target_id:id,payload,change_reason:reason}})}
async function review(type,id,decision,reason=null){return type==='PROVIDER'?request('/rest/v1/rpc/admin_review_provider',{method:'POST',body:{target_id:id,decision,review_reason:reason}}):request('/rest/v1/rpc/admin_review_request',{method:'POST',body:{entity_type:type,target_id:id,decision,review_reason:reason}})}
async function saveProvider(id,payload,reason='Admin provider workspace save'){return request('/rest/v1/rpc/admin_save_provider_workspace',{method:'POST',body:{target_id:id,payload,change_reason:reason}})}
async function providerWorkspace(id){return request('/rest/v1/rpc/admin_provider_workspace',{method:'POST',body:{target_id:id}})}
async function providers(status=null,search=null){return request('/rest/v1/rpc/admin_provider_directory',{method:'POST',body:{status_filter:status,search_text:search}})}
async function saveDeliveryPeople(id,people){return request('/rest/v1/rpc/admin_save_delivery_people',{method:'POST',body:{target_provider_id:id,people}})}
async function uploadMedia(id,itemId,type,file,alt,isPrimary=false){const path=`${id}/admin/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;const headers={apikey:c.supabaseAnonKey,Authorization:`Bearer ${token}`,'Content-Type':file.type,'x-upsert':'false'};const response=await fetch(`${c.supabaseUrl}/storage/v1/object/provider-media/${path}`,{method:'POST',headers,body:file});if(!response.ok)throw new Error((await response.json().catch(()=>({}))).message||'Photo upload failed');return request('/rest/v1/rpc/admin_register_provider_media',{method:'POST',body:{target_provider_id:id,target_menu_item_id:itemId,media_kind:type,object_path:path,mime:file.type,bytes:file.size,alt_text_value:alt,is_primary_value:isPrimary}})}
async function replaceMenu(id,menu){return request('/rest/v1/rpc/admin_replace_provider_menu',{method:'POST',body:{target_provider_id:id,menu_payload:menu}})}
async function enrichItem(id,details){return request('/rest/v1/rpc/admin_enrich_menu_item',{method:'POST',body:{target_item_id:id,item_description:details.description,ingredient_list:details.ingredients,allergen_list:details.allergens,nutrition:details.nutrition}})}
async function mediaUrl(path){const r=await fetch(`${c.supabaseUrl}/storage/v1/object/authenticated/provider-media/${path}`,{headers:{apikey:c.supabaseAnonKey,Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error('Could not load photo');return URL.createObjectURL(await r.blob())}
async function updateMedia(id,alt,status,type,itemId=null){return request('/rest/v1/rpc/admin_update_provider_media',{method:'POST',body:{target_media_id:id,new_alt_text:alt,new_status:status,new_media_type:type,new_menu_item_id:itemId}})}
async function saveFormDraft(id,scope,payload){return request('/rest/v1/rpc/save_provider_form_draft',{method:'POST',body:{target_provider_id:id,scope_name:scope,draft_payload:payload}})}
async function getFormDraft(id,scope){return request('/rest/v1/rpc/get_provider_form_draft',{method:'POST',body:{target_provider_id:id,scope_name:scope}})}
async function payoutQueue(status=null,search=null){return request('/rest/v1/rpc/admin_payout_queue',{method:'POST',body:{status_filter:status,search_text:search}})}
async function payoutDetail(id){return request('/rest/v1/rpc/admin_payout_detail',{method:'POST',body:{target_request:id}})}
async function reviewPayout(id,status,paymentReference=null,note=null){return request('/rest/v1/rpc/admin_review_provider_payout',{method:'POST',body:{target_request:id,target_status:status,target_payment_reference:paymentReference,target_note:note}})}
async function financeSettings(){return request('/rest/v1/finance_configuration?select=payout_hold_hours,updated_at&singleton=eq.true')}
async function setPayoutHold(hours){return request('/rest/v1/rpc/admin_set_payout_hold_hours',{method:'POST',body:{target_hours:hours}})}
async function financeTestCandidates(){return request('/rest/v1/rpc/admin_finance_test_candidates',{method:'POST',body:{}})}
async function createFinanceTest(providerId,grossPaise){return request('/rest/v1/rpc/admin_create_finance_test_cycle',{method:'POST',body:{target_provider:providerId,target_gross_paise:grossPaise}})}
async function clearFinanceTest(providerId=null){return request('/rest/v1/rpc/admin_clear_finance_test_data',{method:'POST',body:{target_provider:providerId}})}
async function advanceQueue(status=null){return request('/rest/v1/rpc/admin_advance_queue',{method:'POST',body:{status_filter:status}})}
async function reviewAdvance(id,status,paymentReference=null,note=null){return request('/rest/v1/rpc/admin_review_provider_advance',{method:'POST',body:{target_request:id,target_status:status,target_payment_reference:paymentReference,target_note:note}})}
async function setAdvanceApprovedAmount(id,amountPaise,note){return request('/rest/v1/rpc/admin_set_advance_approved_amount',{method:'POST',body:{target_request:id,target_approved_amount_paise:amountPaise,target_note:note}})}
async function allocateAdvance(providerId,amountPaise,purpose,paymentReference,note=null){return request('/rest/v1/rpc/admin_allocate_provider_advance',{method:'POST',body:{target_provider:providerId,target_amount_paise:amountPaise,target_purpose:purpose,target_payment_reference:paymentReference,target_note:note}})}
async function providerCommission(providerId=null){return request('/rest/v1/rpc/provider_commission_summary',{method:'POST',body:{target_provider:providerId}})}
async function setProviderCommission(providerId,basisPoints,note,agreed=true){return request('/rest/v1/rpc/admin_set_provider_commission',{method:'POST',body:{target_provider:providerId,target_basis_points:basisPoints,target_note:note,target_agreed:agreed}})}
async function payoutDestinationQueue(status=null){return request('/rest/v1/rpc/admin_payout_destination_queue',{method:'POST',body:{target_status:status}})}
async function reviewPayoutDestination(id,status,note=null){return request('/rest/v1/rpc/admin_review_payout_destination',{method:'POST',body:{target_destination:id,target_status:status,target_note:note}})}
async function financeReconciliation(fromDate,toDate){return request('/rest/v1/rpc/admin_finance_reconciliation',{method:'POST',body:{target_from:fromDate,target_to:toDate}})}
async function recordExternalTransaction(type,reference,amountPaise,occurredAt,status='SETTLED',note=null){return request('/rest/v1/rpc/admin_record_external_transaction',{method:'POST',body:{target_type:type,target_reference:reference,target_amount_paise:amountPaise,target_occurred_at:occurredAt,target_status:status,target_note:note}})}
async function reverseFinanceJournal(entryId,reason){return request('/rest/v1/rpc/admin_reverse_finance_journal',{method:'POST',body:{target_entry:entryId,target_reason:reason}})}
async function providerChangeQueue(status='PENDING',search=null){return request('/rest/v1/rpc/admin_provider_change_queue',{method:'POST',body:{status_filter:status,search_text:search}})}
async function providerChangeDetail(id){return request('/rest/v1/rpc/admin_provider_change_detail',{method:'POST',body:{target_request:id}})}
async function saveProviderChange(id,payload,note=null){return request('/rest/v1/rpc/admin_save_provider_change_request',{method:'POST',body:{target_request:id,revised_payload:payload,target_note:note}})}
async function reviewProviderChange(id,decision,note,payload){return request('/rest/v1/rpc/admin_review_provider_business_update',{method:'POST',body:{target_request:id,target_decision:decision,target_note:note,revised_payload:payload}})}
async function websiteLeads(status=null,search=null){return request('/rest/v1/rpc/admin_website_leads',{method:'POST',body:{status_filter:status,search_text:search}})}
async function updateWebsiteLead(id,status){return request('/rest/v1/rpc/admin_update_website_lead',{method:'POST',body:{target_lead:id,target_status:status}})}
async function businessDashboard(fromDate,toDate){return request('/rest/v1/rpc/admin_business_dashboard',{method:'POST',body:{target_from:fromDate,target_to:toDate}})}
return{configured,login,restore,logout,queue,createProvider,updateProvider,review,saveProvider,providerWorkspace,providers,saveDeliveryPeople,uploadMedia,replaceMenu,enrichItem,mediaUrl,updateMedia,saveFormDraft,getFormDraft,payoutQueue,payoutDetail,reviewPayout,financeSettings,setPayoutHold,financeTestCandidates,createFinanceTest,clearFinanceTest,advanceQueue,reviewAdvance,setAdvanceApprovedAmount,allocateAdvance,providerCommission,setProviderCommission,payoutDestinationQueue,reviewPayoutDestination,financeReconciliation,recordExternalTransaction,reverseFinanceJournal,providerChangeQueue,providerChangeDetail,saveProviderChange,reviewProviderChange,websiteLeads,updateWebsiteLead,businessDashboard}})();
