(() => {
  const api=window.ZomealAPI,nav=document.querySelector('#lowWalletNav'),dashboard=document.querySelector('#dashboard');
  const view=document.createElement('section');view.id='lowWalletView';view.className='view hidden';
  view.innerHTML=`<div class="low-wallet-head"><div><h2>Low wallet follow-ups</h2><p>Customers below ₹500 who may need help recharging before their next meal.</p></div><button id="notifyAllLowWallet" class="primary">Notify all low-wallet users</button></div>
    <section class="panel low-wallet-tools"><div class="input-search">⌕ <input id="lowWalletSearch" type="search" placeholder="Search name, phone or user ID"></div><button id="refreshLowWallet">↻ Refresh</button></section>
    <div id="lowWalletSummary" class="account-notice" role="status" aria-live="polite">Loading low-wallet customers…</div><section id="lowWalletList" class="low-wallet-list"></section>`;
  document.querySelector('#overviewView').parentElement.append(view);
  const list=view.querySelector('#lowWalletList'),summary=view.querySelector('#lowWalletSummary'),search=view.querySelector('#lowWalletSearch');
  let page=0,sequence=0,accessSequence=0;
  const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=value=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(Number(value||0)/100);
  const phoneHref=value=>`tel:+91${String(value||'').replace(/\D/g,'').slice(-10)}`;
  async function checkAccess(){const revision=++accessSequence;if(dashboard.classList.contains('hidden')){nav.classList.add('hidden');view.classList.add('hidden');return}try{const allowed=api.configured&&await api.accountAccess();if(revision===accessSequence)nav.classList.toggle('hidden',!allowed)}catch{if(revision===accessSequence)nav.classList.add('hidden')}}
  new MutationObserver(checkAccess).observe(dashboard,{attributes:true,attributeFilter:['class']});checkAccess();
  nav.onclick=event=>{event.stopPropagation();document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b===nav));document.querySelector('.sidebar').classList.remove('open');document.querySelector('#pageTitle').textContent='Low wallet follow-ups';document.querySelector('#crumb').textContent='Operations / Low wallets';view.classList.remove('hidden');page=0;load()};
  async function load(){const revision=++sequence;summary.textContent='Loading low-wallet customers…';list.innerHTML='';try{const data=await api.lowWalletCustomers(search.value.trim(),page);if(revision!==sequence)return;summary.textContent=`${data.total||0} customer(s) currently have less than ${money(data.threshold_paise)}.`;list.innerHTML=(data.customers||[]).map(customer=>`<article class="panel low-wallet-card" data-id="${escape(customer.id)}"><div class="low-wallet-person"><span>${escape((customer.full_name||'?').trim().charAt(0).toUpperCase())}</span><div><button class="low-wallet-name" data-profile>${escape(customer.full_name||'Unnamed customer')}</button><small>${escape(customer.id)}</small><b>${escape(customer.phone||'No phone saved')}</b></div></div><div><small>Wallet balance</small><strong class="low-balance">${money(customer.balance_paise)}</strong><small>Next meal ${customer.next_meal_paise==null?'not scheduled':money(customer.next_meal_paise)}</small></div><div><small>Subscription</small><strong>${escape((customer.subscription_status||'NONE').replaceAll('_',' '))}</strong><small>${escape(customer.provider_name||'No active provider')} · ${escape(customer.package_name||'No package')}</small></div><div class="low-wallet-actions">${customer.phone?`<a href="${phoneHref(customer.phone)}">☎ Call customer</a>`:''}<button data-notify>Send app alert</button></div></article>`).join('')||'<section class="panel low-wallet-empty">No customers match this filter.</section>';
    list.querySelectorAll('[data-profile]').forEach(button=>button.onclick=()=>openProfile(button.closest('[data-id]').dataset.id));
    list.querySelectorAll('[data-notify]').forEach(button=>button.onclick=()=>notifyOne(button,button.closest('[data-id]').dataset.id));
    if(data.total>25){list.insertAdjacentHTML('beforeend',`<div class="account-pages"><button data-prev ${page===0?'disabled':''}>Previous</button><span>Page ${page+1}</span><button data-next ${(page+1)*25>=data.total?'disabled':''}>Next</button></div>`);list.querySelector('[data-prev]').onclick=()=>{page--;load()};list.querySelector('[data-next]').onclick=()=>{page++;load()}}
  }catch(error){summary.textContent=error.message;summary.className='account-error'}}
  async function notifyOne(button,id){button.disabled=true;const old=button.textContent;button.textContent='Sending…';try{await api.notifyLowWalletCustomer(id);const push=await api.sendPushNotification({user_ids:[id],app_kind:'CUSTOMER',title:'Please recharge your Zomeal Wallet',body:'Your wallet balance is below ₹500. Recharge now to prevent your meal subscription from being paused.',destination:'wallet'});button.textContent='Alert sent';window.showToast?.(push.sent?`Push sent to ${push.sent} device(s)`:'In-app alert saved; this user has no registered device yet')}catch(error){button.textContent=old;window.showToast?.(error.message);button.disabled=false}}
  function openProfile(id){const accountsNav=document.querySelector('#accountsNav');accountsNav.click();const form=document.querySelector('#accountsView .account-search');if(form){form.elements.query.value=id;form.requestSubmit()}}
  let timer;search.oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>{page=0;load()},300)};view.querySelector('#refreshLowWallet').onclick=load;
  view.querySelector('#notifyAllLowWallet').onclick=async event=>{const button=event.currentTarget;if(!confirm('Send a low-wallet recharge alert to every customer currently below ₹500?'))return;button.disabled=true;button.textContent='Sending alerts…';try{const result=await api.notifyAllLowWalletCustomers();const push=await api.sendPushNotification({audience:'LOW_WALLET_CUSTOMERS',app_kind:'CUSTOMER',title:'Please recharge your Zomeal Wallet',body:'Your wallet balance is below ₹500. Recharge now to prevent your meal subscription from being paused.',destination:'wallet'});window.showToast?.(`In-app alerts: ${result.notified||0} · Push devices: ${push.sent||0}`);await load()}catch(error){window.showToast?.(error.message)}finally{button.disabled=false;button.textContent='Notify all low-wallet users'}};
})();
