(function(){
let seq=0;const allergenOptions=['MILK','EGG','PEANUT','TREE_NUT','SOY','WHEAT','SESAME','MUSTARD','FISH','SHELLFISH'];
function itemCard(v={}){const id=`dish-photo-${++seq}`;return`<article class="dish-editor"><div class="dish-editor-head"><strong>Main course <span class="dish-number"></span></strong><button type="button" class="remove-dish">Remove</button></div><label>Item name *<input class="item-name" required value="${v.name||''}" placeholder="Example: Paneer Butter Masala"></label><div class="item-photo-control"><input id="${id}" class="item-photo" type="file" accept="image/png,image/jpeg,image/webp" hidden><label for="${id}" class="item-photo-button">📷 Upload this item’s photo</label><span class="item-photo-name">No photo selected</span></div><details><summary>＋ Description, ingredients, nutrition & allergens</summary><div class="enrichment-grid"><label>Short description<textarea class="item-description">${v.description||''}</textarea></label><label>Ingredients<input class="item-ingredients" value="${(v.ingredients||[]).join(', ')}"></label><label>Allergens<select class="item-allergens" multiple>${allergenOptions.map(a=>`<option value="${a}">${a.replace('_',' ')}</option>`).join('')}</select></label><label>Calories (kcal)<input class="nutrition-calories" type="number" min="0"></label><label>Protein (g)<input class="nutrition-protein" type="number" min="0" step=".1"></label><label>Carbs (g)<input class="nutrition-carbs" type="number" min="0" step=".1"></label><label>Fat (g)<input class="nutrition-fat" type="number" min="0" step=".1"></label></div></details></article>`}
function dayCard(day,i,slot){return`<section class="manual-day multi-day" data-day="${i+1}" data-slot="${slot}"><header><strong>${day}</strong><span>${slot==='LUNCH'?'Lunch':'Dinner'}</span></header><div class="dish-list">${itemCard()}</div><button type="button" class="add-dish">＋ Add another main course</button><label class="fixed-items-label">Shared fixed/side items<input class="fixed-items" required placeholder="Dal, rice/roti, salad, achar..."></label></section>`}
function renumber(day){day.querySelectorAll('.dish-editor').forEach((card,i)=>{card.querySelector('.dish-number').textContent=i+1;card.querySelector('.remove-dish').hidden=i===0})}
function bindItem(card){card.querySelector('.remove-dish').onclick=()=>{const day=card.closest('.multi-day');card.remove();renumber(day)};const input=card.querySelector('.item-photo');input.onchange=()=>{const file=input.files[0],name=card.querySelector('.item-photo-name');name.textContent=file?file.name:'No photo selected';name.classList.toggle('selected',!!file)}}
function bindDay(day){day.querySelector('.add-dish').onclick=()=>{day.querySelector('.dish-list').insertAdjacentHTML('beforeend',itemCard());bindItem(day.querySelector('.dish-editor:last-child'));renumber(day)};day.querySelectorAll('.dish-editor').forEach(bindItem);renumber(day)}
function rebuild(){const host=document.querySelector('#manualWeek');host.innerHTML=`<div class="menu-editor-section"><h4>☀ Lunch menu</h4>${weekDays.map((d,i)=>dayCard(d,i,'LUNCH')).join('')}</div><div class="menu-editor-section"><h4>☾ Dinner menu</h4>${weekDays.map((d,i)=>dayCard(d,i,'DINNER')).join('')}</div>`;host.querySelectorAll('.multi-day').forEach(bindDay)}
function readDish(card){return{name:card.querySelector('.item-name').value.trim(),description:card.querySelector('.item-description').value.trim(),ingredients:card.querySelector('.item-ingredients').value.split(',').map(x=>x.trim()).filter(Boolean),allergens:[...card.querySelector('.item-allergens').selectedOptions].map(x=>x.value),nutrition:{calories:card.querySelector('.nutrition-calories').value,protein_grams:card.querySelector('.nutrition-protein').value,carbs_grams:card.querySelector('.nutrition-carbs').value,fat_grams:card.querySelector('.nutrition-fat').value},photo:card.querySelector('.item-photo').files[0]||null}}
dayPayload=day=>({day:Number(day.dataset.day),meal_slot:day.dataset.slot,main_courses:[...day.querySelectorAll('.dish-editor')].map(readDish),fixed_items:day.querySelector('.fixed-items').value.trim()});rebuild();
function loadMenu(menu=[]){document.querySelectorAll('.multi-day').forEach(day=>{const source=menu.find(x=>Number(x.day)===Number(day.dataset.day)&&x.meal_slot===day.dataset.slot);if(!source)return;day.querySelector('.dish-list').innerHTML=(source.main_courses?.length?source.main_courses:[{}]).map(itemCard).join('');day.querySelectorAll('.dish-editor').forEach(bindItem);day.querySelector('.fixed-items').value=source.fixed_items||'';renumber(day)})}
window.ZomealMenuBuilder={loadMenu};
document.querySelector('#copyMonday').onclick=()=>{document.querySelectorAll('.menu-editor-section').forEach(section=>{const source=dayPayload(section.querySelector('.multi-day'));section.querySelectorAll('.multi-day').forEach((day,i)=>{if(!i)return;day.querySelector('.dish-list').innerHTML=source.main_courses.map(x=>itemCard(x)).join('');day.querySelectorAll('.dish-editor').forEach(bindItem);day.querySelector('.fixed-items').value=source.fixed_items;renumber(day)})});showToast('Monday structure copied. Select a separate photo for each item.')};
document.querySelector('#editProvider').onclick=()=>{const p=selectedWorkspace?.provider;editingProviderId=p?.id||selectedRequest?.id||null;manualTitle.textContent='Edit provider profile & menus';manualDescription.textContent='Every alternative is a separate item with its own photo and optional details.';const inputs=manualForm.querySelectorAll('input');if(p){manualForm.elements.providerName.value=p.display_name||'';inputs[1].value=p.contact_person_name||'';inputs[2].value=p.support_phone||'';inputs[2].disabled=true;inputs[3].value=p.business_address_line||'';inputs[4].value=p.business_city||'';inputs[5].value=p.business_state||'';[...inputs].find(i=>i.placeholder.includes('751030')).value=(selectedWorkspace.service_areas||[]).map(a=>a.pincode).join(', ')}const days=[...(selectedWorkspace?.menus||[])].sort((a,b)=>(b.days?.length||0)-(a.days?.length||0))[0]?.days||[];document.querySelectorAll('.multi-day').forEach(day=>{const source=days.find(d=>d.day===Number(day.dataset.day)&&d.meal_slot===day.dataset.slot),mains=source?.choices?.filter(c=>c.category==='MAIN_COURSE')||[];day.querySelector('.dish-list').innerHTML=(mains.length?mains:[{}]).map(itemCard).join('');day.querySelectorAll('.dish-editor').forEach(bindItem);day.querySelector('.fixed-items').value=(source?.choices||[]).filter(c=>c.category!=='MAIN_COURSE').map(c=>c.name).join(' · ');renumber(day)});manualModal.classList.remove('hidden')};
document.querySelector('#manualProviderForm').onsubmit=async e=>{e.preventDefault();const payload=providerPayload(e.target),submit=e.submitter,deliveryPhone=prompt('Enter the primary delivery boy’s 10-digit phone number');if(!/^[6-9][0-9]{9}$/.test(deliveryPhone||''))return showToast('A valid delivery phone number is required');const deliveryName=prompt('Delivery person name (optional)')||'';if(editingProviderId)delete payload.support_phone;submit.disabled=true;try{const cleanMenu=payload.menu.map(day=>({...day,main_courses:day.main_courses.map(({photo,...item})=>item)}));const providerId=await ZomealAPI.saveProvider(editingProviderId,{...payload,menu:cleanMenu},editingProviderId?'Admin updated multi-item menu':'Admin created multi-item menu');await ZomealAPI.replaceMenu(providerId,cleanMenu);const workspace=await ZomealAPI.providerWorkspace(providerId),days=[...(workspace.menus||[])].sort((a,b)=>(b.days?.length||0)-(a.days?.length||0))[0]?.days||[];for(const day of payload.menu){const savedDay=days.find(d=>d.day===day.day&&d.meal_slot===day.meal_slot);for(const item of day.main_courses){const saved=(savedDay?.choices||[]).find(c=>c.category==='MAIN_COURSE'&&c.name===item.name);if(!saved)throw new Error(`Could not link ${item.name}`);await ZomealAPI.enrichItem(saved.item_id,item);if(item.photo){if(item.photo.size>5242880)throw new Error(`${item.name} photo exceeds 5 MB`);await ZomealAPI.uploadMedia(providerId,saved.item_id,'MENU_ITEM',item.photo,item.description||item.name,true)}}}await ZomealAPI.saveDeliveryPeople(providerId,[{name:deliveryName,phone:deliveryPhone,is_primary:true}]);manualModal.classList.add('hidden');editingProviderId=null;await loadLiveQueue();navigate('providers');showToast('All courses and their individual photos were linked')}catch(error){showToast(error.message)}finally{submit.disabled=false}};
})();
