(() => {
  const api=window.ZomealAPI,nav=document.querySelector('#providerCleanupNav'),dashboard=document.querySelector('#dashboard');
  const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const view=document.createElement('section');view.id='providerCleanupView';view.className='view hidden';
  view.innerHTML=`<div class="cleanup-heading"><div><h2>Provider test-data purge</h2><p class="muted">You choose which provider profiles are test data. Linked test subscriptions, payments, wallet entries and finance history will also be removed.</p></div><button id="cleanupRefresh" class="primary">↻ Refresh</button></div>
    <section class="panel cleanup-toolbar"><div class="input-search">⌕ <input id="cleanupSearch" type="search" placeholder="Search provider, phone or ID"></div><select id="cleanupFilter"><option value="CANDIDATES">Likely test or draft</option><option value="DRAFT_INACTIVE">Draft and inactive</option><option value="ALL">All providers</option></select></section>
    <div class="cleanup-selection"><span><b id="cleanupSelected">0</b> selected · maximum 25 per purge</span><button id="cleanupReview" class="danger" disabled>Review test-data purge</button></div>
    <div id="cleanupNotice" class="account-notice" role="status"></div><div id="cleanupList" class="cleanup-list"></div>`;
  document.querySelector('#overviewView').parentElement.append(view);
  const dialog=document.createElement('dialog');dialog.className='cleanup-dialog';document.body.append(dialog);
  const list=view.querySelector('#cleanupList'),notice=view.querySelector('#cleanupNotice'),selectedLabel=view.querySelector('#cleanupSelected'),review=view.querySelector('#cleanupReview');
  let rows=[],selected=new Set(),timer;
  const selectionChanged=()=>{selectedLabel.textContent=selected.size;review.disabled=selected.size===0};
  async function checkAccess(){try{nav.classList.toggle('hidden',!(api.configured&&await api.accountAccess()))}catch{nav.classList.add('hidden')}}
  new MutationObserver(checkAccess).observe(dashboard,{attributes:true,attributeFilter:['class']});checkAccess();
  nav.onclick=event=>{event.stopPropagation();document.querySelectorAll('.view').forEach(item=>item.classList.add('hidden'));document.querySelectorAll('#nav button').forEach(button=>button.classList.toggle('active',button===nav));document.querySelector('.sidebar').classList.remove('open');document.querySelector('#pageTitle').textContent='Provider test-data purge';document.querySelector('#crumb').textContent='Administration / Provider test-data purge';view.classList.remove('hidden');load()};
  async function load(){notice.className='account-notice';notice.textContent='Loading provider profiles and linked test-data counts…';list.replaceChildren();selected.clear();selectionChanged();try{const data=await api.providerCleanupCandidates(view.querySelector('#cleanupSearch').value.trim(),view.querySelector('#cleanupFilter').value);rows=data.providers||[];notice.textContent=`${rows.length} provider profile(s) in this view. Protected and financially linked profiles remain selectable because this environment is still in testing.`;render()}catch(error){notice.textContent=error.message;notice.className='account-error'}}
  function render(){list.innerHTML=rows.length?rows.map((row,index)=>{const blockers=row.blockers||[];return `<article class="cleanup-row ${row.protected?'protected':''}"><input type="checkbox" data-select="${index}" aria-label="Select ${escape(row.name)}"><div class="cleanup-main"><div><strong>${escape(row.name||'Unnamed provider')}</strong><span class="cleanup-badge ${row.protected?'keep':row.likely_test?'warning':''}">${row.protected?'Previously marked genuine':row.likely_test?'Likely test/draft':'Review manually'}</span></div><p>${escape(row.phone||'No phone')} · ${escape(row.status)} · ${escape(row.id)}</p><div class="cleanup-facts"><span>${row.package_count} packages</span><span>${row.menu_count} menus</span><span>${row.area_count} areas</span><span>${row.photo_count} photos</span><span>${row.subscription_count} subscriptions</span><span>${row.payment_count} payments</span><span>${row.ledger_count||0} ledger entries</span></div>${blockers.length?`<div class="cleanup-blockers">${blockers.map(escape).join(' · ')}</div>`:''}</div><div class="cleanup-actions"><button data-keep="${index}">${row.protected?'Remove genuine marker':'Mark as genuine'}</button></div></article>`}).join(''):'<div class="empty-state"><strong>No matching provider profiles</strong><p>Try All providers or a different search.</p></div>';
    list.querySelectorAll('[data-select]').forEach(box=>box.onchange=()=>{const id=rows[Number(box.dataset.select)].id;box.checked?selected.add(id):selected.delete(id);selectionChanged()});
    list.querySelectorAll('[data-keep]').forEach(button=>button.onclick=async()=>{const row=rows[Number(button.dataset.keep)],protect=!row.protected;if(!protect&&!confirm(`Remove genuine-provider protection from ${row.name}?`))return;button.disabled=true;try{await api.setProviderCleanupProtection(row.id,protect,protect?'Confirmed as a genuine provider in Provider cleanup':null);await load()}catch(error){notice.textContent=error.message;notice.className='account-error';button.disabled=false}})
  }
  review.onclick=()=>{const chosen=rows.filter(row=>selected.has(row.id)),confirmation=`PURGE ${chosen.length} TEST PROVIDERS`;dialog.innerHTML=`<h2>Purge ${chosen.length} test provider profile${chosen.length===1?'':'s'}?</h2><p class="cleanup-critical"><b>This cannot be undone.</b> It removes each selected business and its linked test subscriptions, meals, payments, wallet entries, payouts, advances and finance journal records. Provider login accounts remain.</p><ul>${chosen.map(row=>`<li>${escape(row.name)} · ${escape(row.status)} · ${row.subscription_count} subscriptions · ${row.payment_count} payments</li>`).join('')}</ul><form><label class="cleanup-ack"><input name="acknowledge" type="checkbox" required> I confirm every selected profile and its linked records are test/demo data.</label><label>Reason<textarea name="reason" minlength="10" maxlength="500" required placeholder="Example: Removing duplicate test profiles before the production pilot"></textarea></label><label>Type <b>${escape(confirmation)}</b><input name="confirmation" autocomplete="off" required></label><div class="cleanup-actions"><button type="button" data-cancel>Cancel</button><button type="submit" class="danger">Permanently purge selected test data</button></div><p role="status"></p></form>`;dialog.querySelector('[data-cancel]').onclick=()=>dialog.close();dialog.querySelector('form').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,button=form.querySelector('[type=submit]'),status=form.querySelector('[role=status]');button.disabled=true;status.textContent='Purging selected test providers and linked records in one transaction…';try{const result=await api.deleteProviderCleanup(chosen.map(row=>row.id),form.elements.confirmation.value,form.elements.reason.value);dialog.close();notice.className='account-notice';notice.textContent=`${result.deleted} test provider profile(s), ${result.subscriptions_removed||0} subscription(s) and ${result.payments_removed||0} payment record(s) permanently removed. Uploaded-file cleanup is queued.`;await load()}catch(error){status.textContent=error.message;button.disabled=false}};dialog.showModal()};
  view.querySelector('#cleanupRefresh').onclick=load;view.querySelector('#cleanupFilter').onchange=load;view.querySelector('#cleanupSearch').oninput=event=>{clearTimeout(timer);timer=setTimeout(load,350)};
})();
