/* Consolidates existing tools; never treats collections as profit. */
(() => {
 const api=window.ZomealAPI,nav=document.querySelector('#nav'),host=document.querySelector('#content'),dashboard=document.querySelector('#dashboard');
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const money=v=>v==null?'Unavailable':new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(Number(v)/100);
 const today=()=>new Date(Date.now()+330*60000).toISOString().slice(0,10);
 const rpc=(name,body)=>api.businessDashboard.workspace(name,body);
 const accounts=document.querySelector('#accountsNav'),notifications=document.querySelector('#notificationsNav');
 accounts.innerHTML='<span>♙</span> User Management';notifications.innerHTML='<span>♢</span> Notifications';
 document.querySelector('#accountsView h2').textContent='User Management';
 const payButton=document.createElement('button');payButton.innerHTML='<span>₹</span> Payments & transactions';payButton.dataset.view='payment-register';
 const reportButton=document.createElement('button');reportButton.innerHTML='<span>▥</span> Business reports';reportButton.dataset.view='business-report';
 nav.querySelector('[data-view=overview]').after(reportButton,accounts,payButton,notifications);
 const financeNav=nav.querySelector('[data-view=payouts]');financeNav.innerHTML='<span>₹</span> Provider settlements <b id="payoutNavCount">0</b>';
 function section(id,title,description){const el=document.createElement('section');el.id=id;el.className='view hidden';el.innerHTML=`<div class="workspace-head"><div><h2>${title}</h2><p>${description}</p></div></div>`;host.append(el);return el;}
 const pay=section('payment-registerView','Payments & transactions','Customer payment amounts, gateway references and current status. Production records only.');
 const report=section('business-reportView','CEO business report','Revenue, commission, marketplace activity and customer health in one place.');
 function controls(el,extra=''){el.insertAdjacentHTML('beforeend',`<form class="panel workspace-controls"><label>From · IST<input name="from" type="date" required></label><label>To · IST<input name="to" type="date" required></label>${extra}<button type="submit">Refresh</button></form><p class="workspace-status" role="status" aria-live="polite"></p>`);const f=el.querySelector('form');f.elements.from.value=today().slice(0,8)+'01';f.elements.to.value=today();return f;}
 const pf=controls(pay,'<label>Status<select name="status"><option value="">All statuses</option>'+['CREATING','CREATED','AUTHORIZED','CAPTURED','FAILED','CANCELLED','REFUNDED','PARTIALLY_REFUNDED'].map(s=>`<option>${s}</option>`).join('')+'</select></label><label>Search<input name="search" maxlength="100" placeholder="Customer, kitchen or gateway reference"></label>');
 pay.insertAdjacentHTML('beforeend','<div class="workspace-shortcuts"><button data-settlements>Provider payouts, advances & reconciliation →</button></div><p class="workspace-note">Dates filter payment creation time in IST. Amount is the original order amount—not the refund amount. Customer wallet deductions are available in User Management → account history. Payment status is read-only and comes from the gateway workflow.</p><div class="panel workspace-table"></div><div class="workspace-pages"></div>');
 pay.querySelector('[data-settlements]').onclick=()=>financeNav.click();
 const rf=controls(report);report.insertAdjacentHTML('beforeend','<div class="workspace-metrics"></div><p class="workspace-note">Collections are customer payments, not Zomeal revenue. Revenue below is platform fees + delivered-meal commission, not company profit. Company expenses and taxes are not included. Active users means enabled customers with an ACTIVE plan covering today—not daily app usage. Counts are current; money follows the selected period. Test payments and flagged test ledger entries are excluded.</p><div class="workspace-shortcuts"><button data-overview>Daily charts & provider performance →</button><button data-users>User Management →</button></div>');
 report.querySelector('[data-overview]').onclick=()=>nav.querySelector('[data-view=overview]').click();report.querySelector('[data-users]').onclick=()=>accounts.click();
 let page=0,pseq=0,rseq=0;
 function dates(f){if(!f.reportValidity())throw Error('Choose dates');if(f.elements.from.value>f.elements.to.value)throw Error('Start date must be before end date');return {target_from:f.elements.from.value,target_to:f.elements.to.value};}
 async function payments(){const seq=++pseq;const status=pay.querySelector('.workspace-status'),table=pay.querySelector('.workspace-table'),pager=pay.querySelector('.workspace-pages');table.textContent='';pager.textContent='';status.textContent='Loading payments…';try{const d=await rpc('admin_payment_register',{...dates(pf),status_filter:pf.elements.status.value,search_text:pf.elements.search.value.trim(),page_number:page});if(seq!==pseq)return;status.textContent=`${d.total} matching payments · page ${page+1}`;table.innerHTML=d.rows.length?'<table><thead><tr><th>Created · IST</th><th>Customer / kitchen</th><th>Gateway references</th><th>Amount</th><th>Status</th><th>Failure detail</th></tr></thead><tbody>'+d.rows.map(r=>`<tr><td>${esc(new Date(r.created_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'}))}</td><td>${esc(r.customer||'Unknown')}<br>${esc(r.provider)}</td><td>${esc(r.gateway_order_id||r.id)}<br>${esc(r.gateway_payment_id||'—')}</td><td>${esc(money(r.amount_paise))}</td><td>${esc(r.status)}</td><td>${esc(r.failure_description||'—')}</td></tr>`).join('')+'</tbody></table>':'No payments match these filters.';pager.innerHTML=`<button ${page===0?'disabled':''}>Previous</button><span>50 records per page</span><button ${(page+1)*50>=d.total?'disabled':''}>Next</button>`;pager.firstElementChild.onclick=()=>{page--;payments()};pager.lastElementChild.onclick=()=>{page++;payments()};}catch(e){if(seq===pseq)status.textContent=e.message;}}
 async function reports(){const seq=++rseq;const status=report.querySelector('.workspace-status'),grid=report.querySelector('.workspace-metrics');grid.textContent='';status.textContent='Loading business report…';try{const d=await rpc('admin_ceo_report',dates(rf));if(seq!==rseq)return;const s=d.summary,c=d.ceo;const cards=[['Customer collections',money(s.period_collected_paise),'Captured production payments'],['Zomeal revenue',money(s.period_zomeal_revenue_paise),'Platform fees + commission; not profit'],['Commission',money(s.period_commission_paise),'Delivered meals, including ledger reversals'],['Platform fees',money(s.period_platform_fee_paise),'Captured customer-paid fees'],['Delivered meal value',money(c.delivered_gmv_paise),'Net of included ledger reversals'],['Provider net earnings',money(c.provider_earnings_paise),'Not the amount paid to bank'],['Registered customers',c.registered_customers,'Saved phone; excludes provider/staff accounts'],['Active customers',c.active_customers,'Unique customers with an active plan today'],['Active providers',s.active_providers,'Current ACTIVE provider records'],['Pending providers',s.pending_providers,'Awaiting approval'],['Blocked customers',c.blocked_customers,'Disabled customer profiles'],['Captured payments',c.captured_payments,'Count in the reporting period'],['Failed payments',c.failed_payments,'Count in the reporting period'],['Service pincodes',s.serviceable_pincodes,'Distinct approved pincodes']];grid.innerHTML=cards.map(([t,v,h])=>`<article><span>${esc(t)}</span><strong>${esc(v??'Unavailable')}</strong><small>${esc(h)}</small></article>`).join('');status.textContent=`${d.from_date} to ${d.to_date} · refreshed ${new Date(d.generated_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST`;}catch(e){if(seq===rseq)status.textContent=e.message;}}
 function open(button,el,load){button.onclick=e=>{e.stopPropagation();document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));nav.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b===button));el.classList.remove('hidden');document.querySelector('.sidebar').classList.remove('open');document.querySelector('#pageTitle').textContent=el.querySelector('h2').textContent;document.querySelector('#crumb').textContent=el.querySelector('h2').textContent;load();};}
 open(payButton,pay,payments);open(reportButton,report,reports);pf.onsubmit=e=>{e.preventDefault();page=0;payments()};rf.onsubmit=e=>{e.preventDefault();reports()};
 new MutationObserver(()=>{if(dashboard.classList.contains('hidden')){pseq++;rseq++;pay.querySelector('.workspace-table').textContent='';report.querySelector('.workspace-metrics').textContent='';pay.classList.add('hidden');report.classList.add('hidden');}}).observe(dashboard,{attributes:true,attributeFilter:['class']});
 // Separate daily meal automation, scheduled categories, and immediate broadcasts.
 const nv=document.querySelector('#notificationsView'),meal=nv.querySelector('.meal-reminder-manager'),campaign=nv.querySelector('.campaign-manager:not(.meal-reminder-manager)'),layout=nv.querySelector('.notification-layout'),heading=nv.querySelector(':scope > .notification-head');
 const tabs=document.createElement('div');tabs.className='workspace-tabs';tabs.setAttribute('aria-label','Notification categories');
 const groups=[['Meal reminders',meal],['Offers',campaign,'OFFER'],['Updates',campaign,'UPDATE'],['Other reminders',campaign,'REMINDER'],['Send now',layout]];
 let selected=0;
 function filterCampaigns(){const category=document.querySelector('#campaignCategory')?.value;nv.querySelectorAll('#campaignList [data-category]').forEach(row=>row.hidden=row.dataset.category!==category);}
 function choose(i){selected=i;groups.forEach((g,j)=>tabs.children[j].setAttribute('aria-pressed',String(i===j)));[meal,campaign,layout].forEach(el=>el?.classList.add('hidden'));groups[i][1]?.classList.remove('hidden');if(heading)heading.classList.toggle('hidden',i!==4);const cat=document.querySelector('#campaignCategory');if(cat&&groups[i][2])cat.value=groups[i][2];filterCampaigns();}
 groups.forEach((g,i)=>{const b=document.createElement('button');b.textContent=g[0];b.onclick=()=>choose(i);tabs.append(b)});nv.prepend(tabs);choose(selected);
 document.querySelector('#campaignCategory').addEventListener('change',()=>{const i=groups.findIndex(g=>g[2]===document.querySelector('#campaignCategory').value);if(i>=0)choose(i);});
 document.querySelector('#campaignForm').addEventListener('reset',()=>{const category=groups[selected]?.[2];if(category)queueMicrotask(()=>{document.querySelector('#campaignCategory').value=category;filterCampaigns();});});
 new MutationObserver(filterCampaigns).observe(document.querySelector('#campaignList'),{childList:true});
})();
