package com.zomeal.provider

import androidx.compose.foundation.background
import androidx.compose.foundation.Image
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import org.json.JSONObject
import java.util.Locale

private val PBrand=Color(0xFF087F43);private val PInk=Color(0xFF14221B);private val PMuted=Color(0xFF68736D);private val PMist=Color(0xFFF0F7F2)
private data class PolicyContent(val title:String,val text:String)

@Composable fun ProviderProfileScreen(repository:SupabaseProviderRepository,onBack:()->Unit,onUploadedData:()->Unit,onManageBusiness:()->Unit,onEarnings:()->Unit,onPayoutDetails:()->Unit,onSignOut:()->Unit){
 var profile by remember{mutableStateOf<JSONObject?>(null)};var commission by remember{mutableStateOf<JSONObject?>(null)};var error by remember{mutableStateOf<String?>(null)};var policy by remember{mutableStateOf<PolicyContent?>(null)};var confirmSignOut by remember{mutableStateOf(false)};var showAgreement by remember{mutableStateOf(false)}
 LaunchedEffect(Unit){repository.loadProviderProfileHub{r,e->profile=r;if(e!=null)error=e};repository.loadCommissionSummary{r,e->commission=r;if(e!=null&&error==null)error=e}}
 policy?.let{c->AlertDialog(onDismissRequest={policy=null},title={Text(c.title,fontWeight=FontWeight.Bold)},text={Text(c.text,fontSize=13.sp,lineHeight=19.sp)},confirmButton={TextButton({policy=null}){Text("Close")}})}
 if(showAgreement)AlertDialog(onDismissRequest={showAgreement=false},icon={Icon(Icons.Outlined.Handshake,null,tint=PBrand)},title={Text("Our agreement",fontWeight=FontWeight.Bold)},text={Column(verticalArrangement=Arrangement.spacedBy(9.dp)){val c=commission;Text(if(c==null)"Agreement details are loading." else "Zomeal commission: ${rate(c.optDouble("rate_percent",14.0))}%",fontSize=14.sp,fontWeight=FontWeight.Bold,color=PInk);if(c!=null)Text(if(c.optBoolean("agreed_by_provider"))"Your negotiated commercial terms are marked as agreed." else "The default terms apply until a negotiated rate is approved.",fontSize=12.sp,lineHeight=17.sp,color=PMuted);if(c?.optString("negotiation_note").orEmpty().isNotBlank())Text(c!!.optString("negotiation_note"),fontSize=11.sp,lineHeight=16.sp,color=PMuted);Text("Commission is deducted once from delivered-meal value. Advances are recovered from net earnings without a second commission deduction.",fontSize=11.sp,lineHeight=16.sp,color=PMuted)}},confirmButton={TextButton({showAgreement=false}){Text("Close")}})
 if(confirmSignOut)AlertDialog(onDismissRequest={confirmSignOut=false},icon={Icon(Icons.Outlined.Logout,null,tint=PBrand)},title={Text("Sign out of provider app?")},text={Text("Saved drafts and submitted business information remain safely stored in Zomeal.")},confirmButton={Button({confirmSignOut=false;onSignOut()},colors=ButtonDefaults.buttonColors(containerColor=Color(0xFFB3261E))){Text("Sign out")}},dismissButton={TextButton({confirmSignOut=false}){Text("Stay logged in")}})
 Scaffold(modifier=Modifier.fillMaxSize().windowInsetsPadding(WindowInsets.safeDrawing),containerColor=Color(0xFFF7FAF7),topBar={Surface(shadowElevation=2.dp){Row(Modifier.fillMaxWidth().height(62.dp).padding(horizontal=8.dp),verticalAlignment=Alignment.CenterVertically){IconButton(onBack){Icon(Icons.Outlined.ArrowBack,"Back",tint=PBrand)};Column{Text("Provider profile",fontSize=20.sp,fontWeight=FontWeight.Bold,color=PInk);Text("Business account and policies",fontSize=10.sp,color=PMuted)}}}}){padding->
  LazyColumn(Modifier.fillMaxSize().padding(padding),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){
   error?.let{item{ProfileNotice(it,true)}}
   if(profile==null)item{Box(Modifier.fillMaxWidth().height(150.dp),contentAlignment=Alignment.Center){CircularProgressIndicator(color=PBrand)}}
   profile?.let{p->
    item{Column(Modifier.fillMaxWidth().clip(RoundedCornerShape(22.dp)).background(Brush.horizontalGradient(listOf(Color(0xFF047A45),Color(0xFF55AF45)))).padding(18.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Row(verticalAlignment=Alignment.CenterVertically){ProviderProfilePhoto(repository,p.optString("profile_photo_path"),Modifier.size(62.dp).clip(CircleShape));Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text(p.optString("provider_name").ifBlank{"Your kitchen"},fontSize=21.sp,fontWeight=FontWeight.ExtraBold,color=Color.White);Text("${p.optString("category").replace('_',' ')} · ${p.optString("city")}",fontSize=11.sp,color=Color.White.copy(alpha=.84f));Text(p.optString("contact_name"),fontSize=10.sp,color=Color.White.copy(alpha=.8f))};Surface(color=Color.White.copy(alpha=.18f),shape=RoundedCornerShape(20.dp)){Text(p.optString("status"),Modifier.padding(horizontal=10.dp,vertical=6.dp),fontSize=9.sp,fontWeight=FontWeight.Bold,color=Color.White)}};Text(listOf(p.optString("address"),p.optString("city"),p.optString("pincode")).filter{it.isNotBlank()}.joinToString(", "),fontSize=11.sp,color=Color.White.copy(alpha=.86f));if(p.optString("description").isNotBlank())Text(p.optString("description"),fontSize=10.sp,lineHeight=15.sp,color=Color.White.copy(alpha=.82f))}}
    item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(9.dp)){ProfileMetric("Subscribers",p.optInt("active_subscribers").toString(),Icons.Outlined.Groups,Modifier.weight(1f));ProfileMetric("Packages",p.optInt("active_packages").toString(),Icons.Outlined.Inventory2,Modifier.weight(1f));ProfileMetric("Pincodes",p.optInt("serviceable_pincodes").toString(),Icons.Outlined.LocationOn,Modifier.weight(1f))}}
    if(p.optInt("pending_change_requests")>0)item{ProfileNotice("${p.optInt("pending_change_requests")} business update is waiting for Zomeal review. Your approved listing remains live.",false)}
   }
   item{ProfileSection("Business management"){ProfileAction(Icons.Outlined.FolderOpen,"My uploaded data","View your approved profile, photos, packages and seven-day menus",onUploadedData);ProfileAction(Icons.Outlined.EditNote,"Manage business","Edit profile, packages, weekly menus and photographs",onManageBusiness);ProfileAction(Icons.Outlined.Handshake,"Our agreement","View your agreed commercial terms and commission"){showAgreement=true};ProfileAction(Icons.Outlined.AccountBalanceWallet,"Earnings & advances","Delivered-meal earnings, payouts and advances",onEarnings);ProfileAction(Icons.Outlined.AccountBalance,"Payout details","Add or verify your settlement bank account or UPI",onPayoutDetails)}}
   item{ProfileSection("Help, legal & policies"){ProfileAction(Icons.Outlined.Description,"Provider terms & conditions","Responsibilities, approval and platform rules"){policy=PolicyContent("Provider terms & conditions","Keep business, menu, pricing, hygiene, capacity and delivery information accurate. Customer-facing changes require Zomeal approval. Providers must fulfil confirmed meals, follow applicable food-safety laws and report service interruptions promptly.")};ProfileAction(Icons.Outlined.Gavel,"Cancellation & service policy","Stopping service, migration and notice rules"){policy=PolicyContent("Cancellation & service policy","A provider cannot stop an active service without Zomeal approval. Advance notice may be required so customers can choose another provider. Confirmed meals and approved refunds remain subject to the operating agreement.")};ProfileAction(Icons.Outlined.PrivacyTip,"Privacy policy","How provider and customer data is handled"){policy=PolicyContent("Privacy policy","Use customer names, phone numbers and addresses only to fulfil Zomeal orders. Do not copy, sell or use customer data for unrelated marketing. Limit access to authorised staff and delivery personnel.")};ProfileAction(Icons.Outlined.HealthAndSafety,"Food safety & photo policy","Hygiene, genuine photos and allergens"){policy=PolicyContent("Food safety & photo policy","Upload genuine photographs of your kitchen and meals. Ingredient, dietary and allergen information must be accurate. Zomeal may reject misleading or unsafe content and suspend listings that create customer risk.")};ProfileAction(Icons.Outlined.SupportAgent,"Contact Zomeal support","Help with approvals, customers, payouts or the app") { policy=PolicyContent("Zomeal support","For the MVP, contact the Zomeal operations team using your registered support channel. In-app calling, WhatsApp and ticket support will be connected before production launch.") }}}
   item{OutlinedButton({confirmSignOut=true},Modifier.fillMaxWidth().height(50.dp),shape=RoundedCornerShape(14.dp),colors=ButtonDefaults.outlinedButtonColors(contentColor=Color(0xFFB3261E))){Icon(Icons.Outlined.Logout,null);Spacer(Modifier.width(7.dp));Text("Sign out",fontWeight=FontWeight.Bold)}}
   item{Text("Zomeal Partner · MVP build",Modifier.fillMaxWidth(),textAlign=TextAlign.Center,fontSize=9.sp,color=PMuted)}
   item{Spacer(Modifier.windowInsetsBottomHeight(WindowInsets.navigationBars))}
  }
 }
}

@Composable fun ProviderUploadedDataScreen(repository:SupabaseProviderRepository,onBack:()->Unit){
 var profile by remember{mutableStateOf<JSONObject?>(null)};var error by remember{mutableStateOf<String?>(null)}
 LaunchedEffect(Unit){repository.loadProviderProfileHub{result,message->profile=result;error=message}}
 Scaffold(modifier=Modifier.fillMaxSize().windowInsetsPadding(WindowInsets.safeDrawing),containerColor=Color(0xFFF7FAF7),topBar={Surface(shadowElevation=2.dp){Row(Modifier.fillMaxWidth().height(62.dp).padding(horizontal=8.dp),verticalAlignment=Alignment.CenterVertically){IconButton(onBack){Icon(Icons.Outlined.ArrowBack,"Back",tint=PBrand)};Column{Text("My uploaded data",fontSize=20.sp,fontWeight=FontWeight.Bold,color=PInk);Text("Approved information visible to customers",fontSize=10.sp,color=PMuted)}}}}){padding->
  LazyColumn(Modifier.fillMaxSize().padding(padding),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){
   error?.let{item{ProfileNotice(it,true)}}
   if(profile==null)item{Box(Modifier.fillMaxWidth().height(180.dp),contentAlignment=Alignment.Center){CircularProgressIndicator(color=PBrand)}}
   profile?.let{p->
    item{ProfileSection("Provider details"){Row(verticalAlignment=Alignment.CenterVertically){ProviderProfilePhoto(repository,p.optString("profile_photo_path"),Modifier.size(64.dp).clip(CircleShape));Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text(p.optString("provider_name").ifBlank{"Your kitchen"},fontSize=18.sp,fontWeight=FontWeight.ExtraBold,color=PInk);Text("${p.optString("category").replace('_',' ')} · ${p.optString("status")}",fontSize=10.sp,color=PBrand);Text(p.optString("contact_name"),fontSize=10.sp,color=PMuted)}};Text(listOf(p.optString("address"),p.optString("city"),p.optString("state"),p.optString("pincode")).filter{it.isNotBlank()}.joinToString(", "),fontSize=11.sp,lineHeight=16.sp,color=PMuted);if(p.optString("description").isNotBlank())Text(p.optString("description"),fontSize=11.sp,lineHeight=16.sp,color=PMuted)}}
    item{ProviderPhotoGallery(repository,p)}
    item{ProviderPackageSummary(p)}
    item{ProviderWeeklyMenuSummary(repository,p)}
   }
   item{Spacer(Modifier.windowInsetsBottomHeight(WindowInsets.navigationBars))}
  }
 }
}
@Composable private fun ProviderProfilePhoto(repository:SupabaseProviderRepository,path:String,modifier:Modifier){var bitmap by remember(path){mutableStateOf<android.graphics.Bitmap?>(null)};LaunchedEffect(path){repository.approvedMedia(path){bitmap=it}};Box(modifier.background(Color.White.copy(alpha=.18f)),contentAlignment=Alignment.Center){bitmap?.let{Image(it.asImageBitmap(),null,Modifier.fillMaxSize(),contentScale=ContentScale.Crop)}?:Icon(Icons.Outlined.Storefront,null,tint=Color.White,modifier=Modifier.size(28.dp))}}
@Composable private fun ProviderPhotoGallery(repository:SupabaseProviderRepository,p:JSONObject){ProfileSection("Approved business photos"){Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){ProfileGalleryImage(repository,p.optString("kitchen_photo_path"),"Kitchen",Modifier.weight(1f));ProfileGalleryImage(repository,p.optString("meal_photo_path"),"Complete meal",Modifier.weight(1f))};Text("These are the photographs currently visible to customers.",fontSize=9.sp,color=PMuted)}}
@Composable private fun ProfileGalleryImage(repository:SupabaseProviderRepository,path:String,label:String,modifier:Modifier){var bitmap by remember(path){mutableStateOf<android.graphics.Bitmap?>(null)};LaunchedEffect(path){repository.approvedMedia(path){bitmap=it}};Column(modifier){Box(Modifier.fillMaxWidth().height(92.dp).clip(RoundedCornerShape(13.dp)).background(PMist),contentAlignment=Alignment.Center){bitmap?.let{Image(it.asImageBitmap(),label,Modifier.fillMaxSize(),contentScale=ContentScale.Crop)}?:Icon(Icons.Outlined.AddPhotoAlternate,null,tint=PBrand,modifier=Modifier.size(30.dp))};Text(if(path.isBlank())"$label photo not approved" else label,fontSize=9.sp,fontWeight=FontWeight.Bold,color=if(path.isBlank())PMuted else PInk,modifier=Modifier.padding(top=5.dp))}}
@Composable private fun ProviderPackageSummary(p:JSONObject){val packages=p.optJSONArray("packages")?:org.json.JSONArray();ProfileSection("Packages & prices"){if(packages.length()==0)Text("No active approved packages",fontSize=10.sp,color=PMuted) else for(i in 0 until packages.length()){val item=packages.optJSONObject(i)?:continue;Row(Modifier.fillMaxWidth().padding(vertical=7.dp),verticalAlignment=Alignment.CenterVertically){Icon(if(item.optString("kind")=="DINNER_ONLY")Icons.Outlined.DarkMode else if(item.optString("kind")=="LUNCH_ONLY")Icons.Outlined.LightMode else Icons.Outlined.Restaurant,null,tint=PBrand,modifier=Modifier.size(20.dp));Spacer(Modifier.width(9.dp));Column(Modifier.weight(1f)){Text(item.optString("name"),fontSize=12.sp,fontWeight=FontWeight.Bold,color=PInk);Text("${item.optInt("duration_days",30)} days · ${item.optString("kind").replace('_',' ')}",fontSize=9.sp,color=PMuted)};Text("₹${"%,d".format(item.optLong("price_paise")/100)}",fontSize=13.sp,fontWeight=FontWeight.ExtraBold,color=PBrand)}}}}
@Composable private fun ProviderWeeklyMenuSummary(repository:SupabaseProviderRepository,p:JSONObject){val rows=p.optJSONArray("weekly_menu")?:org.json.JSONArray();ProfileSection("Approved seven-day menu"){if(rows.length()==0)Text("No approved menu is currently live. Contact Zomeal before accepting customers.",fontSize=10.sp,lineHeight=15.sp,color=Color(0xFFB3261E)) else for(i in 0 until rows.length()){val row=rows.optJSONObject(i)?:continue;val day=listOf("Mon","Tue","Wed","Thu","Fri","Sat","Sun").getOrElse(row.optInt("day_of_week")-1){"Day"};val items=row.optJSONArray("items")?:org.json.JSONArray();val mains=buildList<JSONObject>{for(j in 0 until items.length()){val item=items.optJSONObject(j)?:continue;if(item.optString("category").equals("MAIN_COURSE",true))add(item)}};val sides=buildList<String>{for(j in 0 until items.length()){val item=items.optJSONObject(j)?:continue;if(!item.optString("category").equals("MAIN_COURSE",true)&&item.optString("name").isNotBlank())add(item.optString("name"))}};Text("$day · ${row.optString("meal_slot").lowercase().replaceFirstChar{it.uppercase()}}",fontSize=11.sp,fontWeight=FontWeight.ExtraBold,color=PBrand,modifier=Modifier.padding(top=10.dp));if(mains.isEmpty())Text("No approved main course",fontSize=9.sp,color=PMuted) else Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){mains.take(2).forEachIndexed{index,item->Column(Modifier.weight(1f)){ProfileGalleryImage(repository,item.optString("photo_path").takeUnless{it=="null"}.orEmpty(),item.optString("name"),Modifier.fillMaxWidth());Text("Option ${index+1} · ${item.optString("dietary_type").replace('_',' ')}",fontSize=8.sp,color=PMuted);val description=item.optString("description").takeUnless{it=="null"}.orEmpty();if(description.isNotBlank())Text(description,fontSize=8.sp,maxLines=2,color=PMuted)}}};if(mains.size>2)Text("+ ${mains.size-2} more main-course option(s)",fontSize=8.sp,color=PBrand);if(sides.isNotEmpty())Text("Sides: ${sides.joinToString(" · ")}",fontSize=8.sp,lineHeight=12.sp,color=PMuted,modifier=Modifier.padding(top=5.dp));HorizontalDivider(Modifier.padding(top=8.dp),color=Color(0xFFE5EAE6))}}}
@Composable private fun ProfileMetric(label:String,value:String,icon:ImageVector,modifier:Modifier=Modifier){Column(modifier.clip(RoundedCornerShape(16.dp)).background(Color.White).padding(vertical=14.dp,horizontal=7.dp),horizontalAlignment=Alignment.CenterHorizontally){Icon(icon,null,tint=PBrand,modifier=Modifier.size(21.dp));Spacer(Modifier.height(5.dp));Text(value,fontSize=20.sp,fontWeight=FontWeight.ExtraBold,color=PBrand);Text(label,fontSize=8.sp,color=PMuted,maxLines=1)}}
@Composable private fun ProfileSection(title:String,content:@Composable ColumnScope.()->Unit){Column(Modifier.fillMaxWidth().clip(RoundedCornerShape(18.dp)).background(Color.White).padding(15.dp),verticalArrangement=Arrangement.spacedBy(4.dp)){Text(title,fontSize=15.sp,fontWeight=FontWeight.Bold,color=PInk);Spacer(Modifier.height(3.dp));content()}}
@Composable private fun ProfileAction(icon:ImageVector,title:String,subtitle:String,onClick:()->Unit){Row(Modifier.fillMaxWidth().clip(RoundedCornerShape(12.dp)).clickable(onClick=onClick).padding(vertical=10.dp,horizontal=5.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(38.dp).clip(CircleShape).background(PMist),contentAlignment=Alignment.Center){Icon(icon,null,tint=PBrand,modifier=Modifier.size(20.dp))};Spacer(Modifier.width(10.dp));Column(Modifier.weight(1f)){Text(title,fontSize=13.sp,fontWeight=FontWeight.SemiBold,color=PInk);Text(subtitle,fontSize=9.sp,lineHeight=13.sp,color=PMuted)};Icon(Icons.Outlined.ChevronRight,null,tint=PMuted,modifier=Modifier.size(18.dp))}}
@Composable private fun ProfileNotice(message:String,error:Boolean){Text(message,color=if(error)Color(0xFFB3261E) else PBrand,fontSize=10.sp,lineHeight=15.sp,modifier=Modifier.fillMaxWidth().background(if(error)Color(0xFFFFEDEA) else Color(0xFFE7F5EA),RoundedCornerShape(13.dp)).padding(13.dp))}
private fun rate(v:Double)=if(v%1.0==0.0)v.toInt().toString() else String.format(Locale.US,"%.2f",v).trimEnd('0').trimEnd('.')
