const cfg=window.ZOMEAL_WEB_CONFIG;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const grid=$("#provider-grid"),state=$("#search-state"),count=$("#result-count"),providerDialog=$("#provider-dialog"),leadDialog=$("#lead-dialog");
const money=p=>`₹${Math.round(Number(p||0)/100).toLocaleString("en-IN")}`;
const label=s=>String(s||"").replaceAll("_"," ").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
const days=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
let latestProviders=[];

function loading(){grid.innerHTML="";state.hidden=false;state.innerHTML='<div class="loading-ring"></div><h3>Looking for kitchens…</h3><p>Checking approved providers in your area.</p>';count.hidden=true}
function sorry(pin){grid.innerHTML="";state.hidden=false;state.innerHTML=`<div class="sorry-art">🥣</div><h3>Our tiffin took a wrong turn</h3><p>Sorry, Zomeal has no approved provider serving <b>${pin}</b> yet.</p><button class="nav-cta" data-open-lead>Notify me when Zomeal arrives</button>`;bindLeadButtons();count.hidden=true}
function failed(message){grid.innerHTML="";state.hidden=false;state.innerHTML=`<div class="sorry-art">🍛</div><h3>That did not cook properly</h3><p>${message}</p><button class="nav-cta" onclick="document.getElementById('hero-search').requestSubmit()">Try again</button>`;count.hidden=true}
function card(p,i){const packages=p.packages||[],from=packages.length?Math.min(...packages.map(x=>Number(x.price_paise||0))):0;const img=p.primary_photo_url||p.meal_photo_url;return `<article class="provider-card reveal" style="animation-delay:${i*.07}s"><div class="provider-photo">${img?`<img src="${img}" alt="${p.display_name} approved photograph">`:'<div class="fallback">🍱</div>'}<span class="verified">✓ ZOMEAL REVIEWED</span></div><div class="provider-body"><h3>${p.display_name}</h3><p>⌖ ${p.locality||p.city||"Your area"}</p><div class="chips"><span class="chip">${label(p.dietary_type)}</span><span class="chip">${packages.length} plan${packages.length===1?"":"s"}</span></div><div class="price-line"><div><small>Plans from</small><br><b>${money(from)}</b><small> / month</small></div><button data-provider="${p.provider_id}">View details</button></div></div></article>`}
async function search(pin){if(!/^[1-9][0-9]{5}$/.test(pin)){failed("Please enter a valid six-digit Indian pincode.");return}loading();location.hash="providers";try{const res=await fetch(`${cfg.supabaseUrl}/functions/v1/website-provider-search`,{method:"POST",headers:{"Content-Type":"application/json",apikey:cfg.supabasePublishableKey},body:JSON.stringify({pincode:pin})});const body=await res.json();if(!res.ok)throw new Error(body.error||"Search failed");latestProviders=body.providers||[];if(!latestProviders.length){sorry(pin);return}state.hidden=true;count.hidden=false;count.textContent=`${latestProviders.length} provider${latestProviders.length===1?"":"s"} found`;grid.innerHTML=latestProviders.map(card).join("");$$('[data-provider]').forEach(b=>b.onclick=()=>showProvider(b.dataset.provider))}catch(e){failed(e.message||"Please try again.")}}
function showProvider(id){const p=latestProviders.find(x=>x.provider_id===id);if(!p)return;const photo=p.meal_photo_url||p.primary_photo_url;const packages=(p.packages||[]).map(x=>`<div class="detail-package"><b>${x.name}</b><br><span>${money(x.price_paise)} / month</span></div>`).join("");const menu=(p.weekly_menu||[]).map(row=>`<div class="menu-day"><b>${days[(row.day_of_week||1)-1]}</b><span>${label(row.meal_slot)}</span><span>${(row.items||[]).map(i=>i.name).join(" · ")}</span></div>`).join("");$("#provider-detail").innerHTML=`<div class="detail-cover">${photo?`<img src="${photo}" alt="Approved meal from ${p.display_name}">`:"🍱"}</div><div class="detail-title"><h2>${p.display_name}</h2><p>⌖ ${p.locality||""}${p.locality&&p.city?", ":""}${p.city||""} · ✓ Zomeal reviewed</p></div><h3>Available packages</h3><div class="detail-packages">${packages||"Package information coming soon"}</div><div class="detail-menu"><h3>Approved weekly menu</h3>${menu||"<p>Menu details are being prepared.</p>"}</div><p><b>Subscriptions are not available on this website.</b> Join early access to hear when our Android app launches.</p><button class="submit-lead" data-open-lead>Notify me at launch →</button>`;providerDialog.showModal();bindLeadButtons()}
$("#hero-search").onsubmit=e=>{e.preventDefault();search($("#hero-pincode").value.trim())};
function bindLeadButtons(){$$("[data-open-lead]").forEach(b=>b.onclick=()=>{if(providerDialog.open)providerDialog.close();const pin=$("#hero-pincode").value.trim(),pinField=$('[name="lead_pincode"]',leadDialog);if(pin&&pinField)pinField.value=pin;leadDialog.showModal()})}
bindLeadButtons();$$('[data-close-dialog]').forEach(b=>b.onclick=()=>b.closest("dialog").close());
$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close()}));
$("#lead-form").onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,button=$(".submit-lead",form),message=$("#lead-message");button.disabled=true;message.textContent="Saving your place…";const data=Object.fromEntries(new FormData(form));data.accepted_consent=Boolean(new FormData(form).get("accepted_consent"));try{const res=await fetch(`${cfg.supabaseUrl}/rest/v1/rpc/website_join_waitlist`,{method:"POST",headers:{apikey:cfg.supabasePublishableKey,"Content-Type":"application/json"},body:JSON.stringify(data)});const body=await res.json();if(!res.ok)throw new Error(body.message||body.error||"Could not save your details");message.textContent="✓ You’re on the list! We’ll keep you posted.";form.reset();setTimeout(()=>leadDialog.close(),1800)}catch(err){message.textContent=err.message}finally{button.disabled=false}};
